-- Script de Diagnóstico para PUBROCK_CR
-- Ejecuta este script en SQL Server Management Studio contra la BD PUBROCK_CR
-- Ayudará a identificar el estado actual del schema y los datos

-- 1. Verificar si existe la tabla PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB
IF OBJECT_ID('dbo.PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB', 'U') IS NOT NULL
	SELECT 'PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB existe' AS [Status];
ELSE
	SELECT 'ERROR: PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB NO EXISTE' AS [Status];

-- 2. Verificar si existe el registro 'Egreso'
SELECT 
	ISNULL(COUNT(*), 0) AS [Cantidad_Egreso]
FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB 
WHERE DESCRIPCION = 'Egreso';

-- 3. Listar todos los tipos de movimiento existentes
SELECT 
	ID_TIPO_MOVIMIENTO_FINANCIERO,
	DESCRIPCION,
	ID_ESTADO
FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB
ORDER BY ID_TIPO_MOVIMIENTO_FINANCIERO;

-- 4. Verificar columnas de PUBROCK_MOVIMIENTO_FINANCIERO_TB
IF OBJECT_ID('dbo.PUBROCK_MOVIMIENTO_FINANCIERO_TB', 'U') IS NOT NULL
BEGIN
	SELECT 
		COLUMN_NAME,
		DATA_TYPE,
		IS_NULLABLE
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'PUBROCK_MOVIMIENTO_FINANCIERO_TB'
	ORDER BY ORDINAL_POSITION;
END
ELSE
	SELECT 'ERROR: PUBROCK_MOVIMIENTO_FINANCIERO_TB NO EXISTE' AS [Status];

-- 5. Verificar si existe la tabla PUBROCK_BITACORA_TB y la columna MODULO
IF OBJECT_ID('dbo.PUBROCK_BITACORA_TB', 'U') IS NOT NULL
BEGIN
	SELECT 
		ISNULL(COUNT(*), 0) AS [Tiene_Columna_MODULO]
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'PUBROCK_BITACORA_TB'
	AND COLUMN_NAME = 'MODULO';
END
ELSE
	SELECT 'ERROR: PUBROCK_BITACORA_TB NO EXISTE' AS [Status];

-- 6. Resumen general
SELECT 'DIAGNÓSTICO EJECUTADO' AS [Completado];
