/* =====================================================================
   PUBROCK_CR.sql
   Base de datos del sistema de administracion del restaurante PUBROCK
   Version revisada por: Arquitectura de Datos Senior
   Motor: SQL Server 2016+
   Compatibilidad: proyecto C# .NET Framework 4.8.1 (se conservan TODOS
   los nombres de tablas y columnas existentes)
   ===================================================================== */

-- =====================================================================
-- SECCION 0: CREACION DE LA BASE DE DATOS
-- =====================================================================
IF DB_ID('PUBROCK_CR') IS NOT NULL
BEGIN
    ALTER DATABASE PUBROCK_CR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PUBROCK_CR;
END;
GO

-- =====================================================================
-- PROCEDIMIENTO: REPORTE DE INVENTARIO
-- Devuelve estado actual del inventario con indicadores
-- =====================================================================
IF OBJECT_ID('SP_PUBROCK_REPORTE_INVENTARIO', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_REPORTE_INVENTARIO;
GO

CREATE PROCEDURE SP_PUBROCK_REPORTE_INVENTARIO
    @IdCategoria INT = NULL,
    @IdProveedor INT = NULL,
    @IdEstado INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        p.ID_PRODUCTO AS Codigo,
        p.NOMBRE_PRODUCTO AS Producto,
        p.ID_CATEGORIA_PRODUCTO AS Categoria,
        i.STOCK_ACTUAL AS StockActual,
        i.STOCK_MINIMO AS StockMinimo,
        i.STOCK_MAXIMO AS StockMaximo,
        ISNULL(p.PRECIO_VENTA, 0) AS Precio,
        CASE
            WHEN i.STOCK_ACTUAL <= 0 THEN 'Sin Existencias'
            WHEN i.STOCK_ACTUAL <= i.STOCK_MINIMO THEN 'Stock Bajo'
            ELSE 'Disponible'
        END AS EstadoInventario
    FROM PUBROCK_PRODUCTO_TB p
    LEFT JOIN PUBROCK_INVENTARIO_TB i ON p.ID_PRODUCTO = i.ID_PRODUCTO
    WHERE (@IdCategoria IS NULL OR p.ID_CATEGORIA_PRODUCTO = @IdCategoria)
      AND (@IdProveedor IS NULL OR p.ID_PROVEEDOR = @IdProveedor)
      AND (@IdEstado IS NULL OR (
            CASE
                WHEN i.STOCK_ACTUAL <= 0 THEN 3
                WHEN i.STOCK_ACTUAL <= i.STOCK_MINIMO THEN 2
                ELSE 1
            END) = @IdEstado)
    ORDER BY p.NOMBRE_PRODUCTO;
END
GO

CREATE DATABASE PUBROCK_CR;
GO

USE PUBROCK_CR;
GO

-- Habilita a 'sa' como propietario de la base para evitar el error
-- "Error no especificado" al crear diagramas de base de datos en SSMS.
-- (Se conserva porque es inofensivo; se retiraron mas adelante todos
--  los comandos verdaderamente peligrosos del script original.)
ALTER AUTHORIZATION ON DATABASE::PUBROCK_CR TO sa;
GO


-- =====================================================================
-- SECCION 1: TABLA MAESTRA DE ESTADOS
-- Todas las tablas del sistema usan ID_ESTADO como bandera logica de
-- activo/inactivo (borrado logico). Se crea primero porque es
-- referenciada por practicamente todo el modelo.
-- =====================================================================
CREATE TABLE PUBROCK_ESTADO_TB (
    ID_ESTADO   INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PUBROCK_ESTADO_TB PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UQ_PUBROCK_ESTADO_DESCRIPCION UNIQUE (DESCRIPCION)
);
GO

-- Datos base indispensables: sin estos registros, cualquier INSERT
-- posterior que use ID_ESTADO = 1 fallaria por violacion de FK.
-- (En el script original esta carga faltaba por completo.)
INSERT INTO PUBROCK_ESTADO_TB (DESCRIPCION) VALUES
('Activo'),
('Inactivo');
GO


-- =====================================================================
-- SECCION 2: UBICACIONES GEOGRAFICAS (jerarquia Pais -> Provincia ->
-- Canton -> Distrito). Se agregan las relaciones jerarquicas faltantes
-- solicitadas (mejora de integridad referencial), sin eliminar ni
-- renombrar ninguna columna existente.
-- =====================================================================
CREATE TABLE PUBROCK_PAIS_TB (
    ID_PAIS   INT IDENTITY(1,1) NOT NULL,
    NOMBRE    VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PAIS_TB PRIMARY KEY (ID_PAIS),
    CONSTRAINT FK_PUBROCK_PAIS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROVINCIA_TB (
    ID_PROVINCIA INT IDENTITY(1,1) NOT NULL,
    NOMBRE       VARCHAR(100) NOT NULL,
    ID_PAIS      INT NOT NULL,                 -- NUEVO: relacion jerarquica Provincia -> Pais
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROVINCIA_TB PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_PROVINCIA_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PUBROCK_PAIS_TB(ID_PAIS),
    CONSTRAINT FK_PUBROCK_PROVINCIA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CANTON_TB (
    ID_CANTON    INT IDENTITY(1,1) NOT NULL,
    NOMBRE       VARCHAR(100) NOT NULL,
    ID_PROVINCIA INT NOT NULL,                 -- NUEVO: relacion jerarquica Canton -> Provincia
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CANTON_TB PRIMARY KEY (ID_CANTON),
    CONSTRAINT FK_PUBROCK_CANTON_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PUBROCK_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_CANTON_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DISTRITO_TB (
    ID_DISTRITO INT IDENTITY(1,1) NOT NULL,
    NOMBRE      VARCHAR(100) NOT NULL,
    ID_CANTON   INT NOT NULL,                  -- NUEVO: relacion jerarquica Distrito -> Canton
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DISTRITO_TB PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT FK_PUBROCK_DISTRITO_CANTON FOREIGN KEY (ID_CANTON) REFERENCES PUBROCK_CANTON_TB(ID_CANTON),
    CONSTRAINT FK_PUBROCK_DISTRITO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 3: USUARIOS
-- NOTA DE DISENO: en el script original la tabla PUBROCK_USUARIO_TB se
-- creaba SIN las columnas CORREO, TELEFONO y CONTRASENIA, se insertaba
-- un registro que SI las usaba (error de ejecucion garantizado) y
-- recien despues se agregaban esas columnas con ALTER TABLE. Se corrige
-- unificando todas las columnas en el CREATE TABLE y moviendo el
-- INSERT despues de la definicion completa.
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_USUARIO_TB (
    ID_TIPO_USUARIO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION     VARCHAR(100) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_USUARIO_TB PRIMARY KEY (ID_TIPO_USUARIO),
    CONSTRAINT FK_PUBROCK_TIPO_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

INSERT INTO PUBROCK_TIPO_USUARIO_TB (DESCRIPCION, ID_ESTADO) VALUES
('Administrador', 1),
('Empleado', 1),
('Cliente', 1),
('Proveedor', 1);
GO

CREATE TABLE PUBROCK_USUARIO_TB (
    CEDULA            VARCHAR(20) NOT NULL,
    NOMBRE            VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO  VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO  VARCHAR(100),
    FECHA_REGISTRO    DATE NOT NULL DEFAULT GETDATE(),
    ID_TIPO_USUARIO   INT NOT NULL,
    CORREO            VARCHAR(100),
    TELEFONO          VARCHAR(20),
    CONTRASENIA       VARCHAR(255),
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_USUARIO_TB PRIMARY KEY (CEDULA),
    CONSTRAINT FK_PUBROCK_USUARIO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES PUBROCK_TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    CONSTRAINT FK_PUBROCK_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

-- Indice unico "filtrado": permite muchos usuarios sin correo (NULL)
-- pero impide correos duplicados cuando si existen.
CREATE UNIQUE INDEX UQ_PUBROCK_USUARIO_CORREO ON PUBROCK_USUARIO_TB(CORREO) WHERE CORREO IS NOT NULL;
GO

INSERT INTO PUBROCK_USUARIO_TB
(
    CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,
    FECHA_REGISTRO, ID_TIPO_USUARIO, CORREO, TELEFONO, CONTRASENIA, ID_ESTADO
)
VALUES
(
    '123456789', 'Administrador', 'Sistema', 'Principal',
    GETDATE(), 1, 'admin@pubrock.com', '88888888', 'Admin123', 1
);
GO

INSERT INTO PUBROCK_USUARIO_TB
(
    CEDULA,
    NOMBRE,
    APELLIDO_PATERNO,
    APELLIDO_MATERNO,
    FECHA_REGISTRO,
    ID_TIPO_USUARIO,
    ID_ESTADO,
    CORREO,
    TELEFONO,
    CONTRASENIA
)
VALUES
(
    '555555555',
    'Carlos',
    'Ramírez',
    'Soto',
    GETDATE(),
3, 
1, 
'cliente@pubrock.com',
'88886666',
'Cliente123'
);
GO

CREATE TABLE PUBROCK_DIRECCION_TB (
    CEDULA       VARCHAR(20) NOT NULL,
    ID_PAIS      INT,
    ID_PROVINCIA INT,
    ID_CANTON    INT,
    ID_DISTRITO  INT,
    OTRAS_SENAS  VARCHAR(500),
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DIRECCION_TB PRIMARY KEY (CEDULA),
    CONSTRAINT FK_PUBROCK_DIRECCION_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_DIRECCION_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PUBROCK_PAIS_TB(ID_PAIS),
    CONSTRAINT FK_PUBROCK_DIRECCION_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PUBROCK_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_DIRECCION_CANTON FOREIGN KEY (ID_CANTON) REFERENCES PUBROCK_CANTON_TB(ID_CANTON),
    CONSTRAINT FK_PUBROCK_DIRECCION_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES PUBROCK_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FK_PUBROCK_DIRECCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TELEFONO_TB (
    CEDULA    VARCHAR(20) NOT NULL,
    TELEFONO  VARCHAR(20) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TELEFONO_TB PRIMARY KEY (CEDULA, TELEFONO),
    CONSTRAINT FK_PUBROCK_TELEFONO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_TELEFONO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CORREO_ELECTRONICO_TB (
    CEDULA    VARCHAR(20) NOT NULL,
    CORREO    VARCHAR(150) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CORREO_ELECTRONICO_TB PRIMARY KEY (CEDULA, CORREO),
    CONSTRAINT FK_PUBROCK_CORREO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_CORREO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 4: EMPLEADOS
-- NOTA DE DISENO (PK compuesta innecesaria): la tabla original definia
-- PRIMARY KEY (ID_EMPLEADO, CEDULA) y ADEMAS un UNIQUE(ID_EMPLEADO).
-- Si ID_EMPLEADO ya es unico por si solo, la PK compuesta no aporta
-- nada: cualquier busqueda por ID_EMPLEADO (la forma normal de
-- trabajar de una app .NET con Entity/ADO.NET) termina golpeando un
-- indice mas pesado de lo necesario, y la relacion 1 a 1 real con
-- CEDULA se expresa mejor como UNIQUE simple. Se corrige dejando
-- ID_EMPLEADO como PK y CEDULA como UNIQUE + FK. Mismo caso en
-- PUBROCK_PROVEEDOR_TB. Ninguna columna fue eliminada ni renombrada.
-- =====================================================================
CREATE TABLE PUBROCK_PUESTO_TB (
    ID_PUESTO     INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PUESTO VARCHAR(100) NOT NULL,
    DESCRIPCION   VARCHAR(255),
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PUESTO_TB PRIMARY KEY (ID_PUESTO),
    CONSTRAINT FK_PUBROCK_PUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_EMPLEADO_TB (
    ID_EMPLEADO   INT IDENTITY(1,1) NOT NULL,
    FECHA_INGRESO DATE NOT NULL DEFAULT GETDATE(),
    CEDULA        VARCHAR(20) NOT NULL,
    ID_PUESTO     INT NOT NULL,
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_EMPLEADO_TB PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT UQ_PUBROCK_EMPLEADO_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_EMPLEADO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_EMPLEADO_PUESTO FOREIGN KEY (ID_PUESTO) REFERENCES PUBROCK_PUESTO_TB(ID_PUESTO),
    CONSTRAINT FK_PUBROCK_EMPLEADO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_ROL_TB (
    ID_ROL      INT IDENTITY(1,1) NOT NULL,
    NOMBRE_ROL  VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ROL_TB PRIMARY KEY (ID_ROL),
    CONSTRAINT FK_PUBROCK_ROL_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_USUARIO_SISTEMA_TB (
    ID_USUARIO_SISTEMA INT IDENTITY(1,1) NOT NULL,
    NOMBRE_USUARIO     VARCHAR(100) NOT NULL,
    CLAVE              VARCHAR(255) NOT NULL,
    FECHA_REGISTRO     DATE NOT NULL DEFAULT GETDATE(),
    ID_EMPLEADO        INT NOT NULL,
    ID_ROL             INT NOT NULL,
    ID_ESTADO          INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_USUARIO_SISTEMA_TB PRIMARY KEY (ID_USUARIO_SISTEMA),
    CONSTRAINT UQ_PUBROCK_USUARIO_SISTEMA_NOMBRE UNIQUE (NOMBRE_USUARIO),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_ROL FOREIGN KEY (ID_ROL) REFERENCES PUBROCK_ROL_TB(ID_ROL),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_REGISTRO_ACTIVIDAD_TB (
    ID_REGISTRO_ACTIVIDAD INT IDENTITY(1,1) NOT NULL,
    FECHA_HORA            DATETIME NOT NULL DEFAULT GETDATE(),
    ACCION_REALIZADA      VARCHAR(255) NOT NULL,
    DESCRIPCION           VARCHAR(500),
    ID_USUARIO_SISTEMA    INT NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_REGISTRO_ACTIVIDAD_TB PRIMARY KEY (ID_REGISTRO_ACTIVIDAD),
    CONSTRAINT FK_PUBROCK_REGISTRO_ACTIVIDAD_USUARIO_SISTEMA FOREIGN KEY (ID_USUARIO_SISTEMA) REFERENCES PUBROCK_USUARIO_SISTEMA_TB(ID_USUARIO_SISTEMA),
    CONSTRAINT FK_PUBROCK_REGISTRO_ACTIVIDAD_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 5: CLIENTES Y PROVEEDORES
-- =====================================================================
CREATE TABLE PUBROCK_CLIENTE_TB (
    ID_CLIENTE            INT IDENTITY(1,1) NOT NULL,
    FECHA_INGRESO_CLIENTE DATE NOT NULL DEFAULT GETDATE(),
    CEDULA                VARCHAR(20) NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CLIENTE_TB PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_PUBROCK_CLIENTE_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_CLIENTE_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_CLIENTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROVEEDOR_TB (
    ID_PROVEEDOR            INT IDENTITY(1,1) NOT NULL,
    CONTACTO_PRINCIPAL      VARCHAR(100),
    FECHA_INGRESO_PROVEEDOR DATE NOT NULL DEFAULT GETDATE(),
    CEDULA                  VARCHAR(20) NOT NULL,
    ID_ESTADO               INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROVEEDOR_TB PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT UQ_PUBROCK_PROVEEDOR_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_PROVEEDOR_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_PROVEEDOR_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 6: PRODUCTOS E INVENTARIO
-- =====================================================================
CREATE TABLE PUBROCK_CATEGORIA_PRODUCTO_TB (
    ID_CATEGORIA_PRODUCTO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_CATEGORIA      VARCHAR(100) NOT NULL,
    DESCRIPCION           VARCHAR(255),
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CATEGORIA_PRODUCTO_TB PRIMARY KEY (ID_CATEGORIA_PRODUCTO),
    CONSTRAINT FK_PUBROCK_CATEGORIA_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PRODUCTO_TB (
    ID_PRODUCTO            INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PRODUCTO        VARCHAR(100) NOT NULL,
    DESCRIPCION            VARCHAR(255),
    CODIGO_BARRAS          VARCHAR(100),
    PRECIO_VENTA           DECIMAL(10,2) NOT NULL DEFAULT 0,
    FECHA_VENCIMIENTO      DATE,
    ID_CATEGORIA_PRODUCTO  INT NOT NULL,
    ID_PROVEEDOR           INT,
    ID_ESTADO              INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PRODUCTO_TB PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_PRODUCTO_PRECIO CHECK (PRECIO_VENTA >= 0),
    CONSTRAINT FK_PUBROCK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES PUBROCK_CATEGORIA_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PRODUCTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PUBROCK_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FK_PUBROCK_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

-- Codigo de barras unico solo cuando existe (muchos productos de menu
-- de un restaurante no tienen codigo de barras real).
CREATE UNIQUE INDEX UQ_PUBROCK_PRODUCTO_CODIGO_BARRAS ON PUBROCK_PRODUCTO_TB(CODIGO_BARRAS) WHERE CODIGO_BARRAS IS NOT NULL;
GO

CREATE TABLE PUBROCK_INVENTARIO_TB (
    ID_INVENTARIO               INT IDENTITY(1,1) NOT NULL,
    STOCK_ACTUAL                INT NOT NULL DEFAULT 0,
    STOCK_MINIMO                INT NOT NULL DEFAULT 0,
    STOCK_MAXIMO                INT NOT NULL DEFAULT 0,
    FECHA_ULTIMA_ACTUALIZACION  DATE NOT NULL DEFAULT GETDATE(),
    ID_PRODUCTO                 INT NOT NULL,
    ID_ESTADO                   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_INVENTARIO_TB PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT UQ_PUBROCK_INVENTARIO_PRODUCTO UNIQUE (ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_ACTUAL CHECK (STOCK_ACTUAL >= 0),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_MINIMO CHECK (STOCK_MINIMO >= 0),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_MAXIMO CHECK (STOCK_MAXIMO >= STOCK_MINIMO),
    CONSTRAINT FK_PUBROCK_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB (
    ID_TIPO_MOVIMIENTO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB PRIMARY KEY (ID_TIPO_MOVIMIENTO),
    CONSTRAINT FK_PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO_INVENTARIO INT IDENTITY(1,1) NOT NULL,
    FECHA_MOVIMIENTO         DATE NOT NULL DEFAULT GETDATE(),
    CANTIDAD                 INT NOT NULL,
    OBSERVACION              VARCHAR(255),
    ID_INVENTARIO            INT NOT NULL,
    ID_TIPO_MOVIMIENTO       INT NOT NULL,
    ID_ESTADO                INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MOVIMIENTO_INVENTARIO_TB PRIMARY KEY (ID_MOVIMIENTO_INVENTARIO),
    CONSTRAINT CK_PUBROCK_MOVIMIENTO_INVENTARIO_CANTIDAD CHECK (CANTIDAD <> 0),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_INVENTARIO FOREIGN KEY (ID_INVENTARIO) REFERENCES PUBROCK_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_TIPO FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 7: COMPRAS
-- =====================================================================
CREATE TABLE PUBROCK_COMPRA_TB (
    ID_COMPRA    INT IDENTITY(1,1) NOT NULL,
    FECHA_COMPRA DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_COMPRA DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_PROVEEDOR INT NOT NULL,
    ID_EMPLEADO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_COMPRA_TB PRIMARY KEY (ID_COMPRA),
    CONSTRAINT CK_PUBROCK_COMPRA_TOTAL CHECK (TOTAL_COMPRA >= 0),
    CONSTRAINT FK_PUBROCK_COMPRA_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PUBROCK_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FK_PUBROCK_COMPRA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_COMPRA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_COMPRA_TB (
    ID_DETALLE_COMPRA INT IDENTITY(1,1) NOT NULL,
    CANTIDAD          INT NOT NULL,
    COSTO_UNITARIO    DECIMAL(10,2) NOT NULL,
    SUBTOTAL          DECIMAL(10,2) NOT NULL,
    ID_COMPRA         INT NOT NULL,
    ID_PRODUCTO       INT NOT NULL,
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_COMPRA_TB PRIMARY KEY (ID_DETALLE_COMPRA),
    CONSTRAINT CK_PUBROCK_DETALLE_COMPRA_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_COMPRA_COSTO CHECK (COSTO_UNITARIO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES PUBROCK_COMPRA_TB(ID_COMPRA),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 8: VENTAS
-- =====================================================================
CREATE TABLE PUBROCK_VENTA_TB (
    ID_VENTA     INT IDENTITY(1,1) NOT NULL,
    FECHA_VENTA  DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_VENTA  DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_CLIENTE   INT,
    ID_EMPLEADO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_VENTA_TB PRIMARY KEY (ID_VENTA),
    CONSTRAINT CK_PUBROCK_VENTA_TOTAL CHECK (TOTAL_VENTA >= 0),
    CONSTRAINT FK_PUBROCK_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_VENTA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_VENTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_VENTA_TB (
    ID_DETALLE_VENTA INT IDENTITY(1,1) NOT NULL,
    CANTIDAD         INT NOT NULL,
    PRECIO_UNITARIO  DECIMAL(10,2) NOT NULL,
    SUBTOTAL         DECIMAL(10,2) NOT NULL,
    ID_VENTA         INT NOT NULL,
    ID_PRODUCTO      INT NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_VENTA_TB PRIMARY KEY (ID_DETALLE_VENTA),
    CONSTRAINT CK_PUBROCK_DETALLE_VENTA_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_VENTA_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 9: FACTURACION
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_PAGO_TB (
    ID_TIPO_PAGO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION  VARCHAR(100) NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_PAGO_TB PRIMARY KEY (ID_TIPO_PAGO),
    CONSTRAINT FK_PUBROCK_TIPO_PAGO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_FACTURA_TB (
    ID_FACTURA     INT IDENTITY(1,1) NOT NULL,
    NUMERO_FACTURA VARCHAR(100) NOT NULL,
    FECHA_FACTURA  DATE NOT NULL DEFAULT GETDATE(),
    MONTO_TOTAL    DECIMAL(10,2) NOT NULL,
    ID_VENTA       INT NOT NULL,
    ID_TIPO_PAGO   INT NOT NULL,
    ID_ESTADO      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_FACTURA_TB PRIMARY KEY (ID_FACTURA),
    CONSTRAINT UQ_PUBROCK_FACTURA_NUMERO UNIQUE (NUMERO_FACTURA),
    CONSTRAINT CK_PUBROCK_FACTURA_MONTO CHECK (MONTO_TOTAL >= 0),
    CONSTRAINT FK_PUBROCK_FACTURA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_FACTURA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES PUBROCK_TIPO_PAGO_TB(ID_TIPO_PAGO),
    CONSTRAINT FK_PUBROCK_FACTURA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 10: DEVOLUCIONES
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_DEVOLUCION_TB (
    ID_TIPO_DEVOLUCION INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_DEVOLUCION_TB PRIMARY KEY (ID_TIPO_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_TIPO_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DEVOLUCION_TB (
    ID_DEVOLUCION       INT IDENTITY(1,1) NOT NULL,
    FECHA_DEVOLUCION    DATE NOT NULL DEFAULT GETDATE(),
    MOTIVO_GENERAL      VARCHAR(255),
    ID_VENTA            INT NOT NULL,
    ID_CLIENTE          INT,
    ID_EMPLEADO         INT NOT NULL,
    ID_TIPO_DEVOLUCION  INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DEVOLUCION_TB PRIMARY KEY (ID_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_TIPO FOREIGN KEY (ID_TIPO_DEVOLUCION) REFERENCES PUBROCK_TIPO_DEVOLUCION_TB(ID_TIPO_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_DEVOLUCION_TB (
    ID_DETALLE_DEVOLUCION INT IDENTITY(1,1) NOT NULL,
    CANTIDAD              INT NOT NULL,
    MONTO_DEVUELTO        DECIMAL(10,2) NOT NULL,
    ID_DEVOLUCION         INT NOT NULL,
    ID_PRODUCTO           INT NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_DEVOLUCION_TB PRIMARY KEY (ID_DETALLE_DEVOLUCION),
    CONSTRAINT CK_PUBROCK_DETALLE_DEVOLUCION_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_DEVOLUCION_MONTO CHECK (MONTO_DEVUELTO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_DEVOLUCION FOREIGN KEY (ID_DEVOLUCION) REFERENCES PUBROCK_DEVOLUCION_TB(ID_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 11: CAJA Y MOVIMIENTOS FINANCIEROS
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (
    ID_TIPO_MOVIMIENTO_FINANCIERO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION                    VARCHAR(100) NOT NULL,
    ID_ESTADO                      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB PRIMARY KEY (ID_TIPO_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_MOVIMIENTO_FINANCIERO_TB (
    ID_MOVIMIENTO_FINANCIERO      INT IDENTITY(1,1) NOT NULL,
    FECHA_MOVIMIENTO              DATE NOT NULL DEFAULT GETDATE(),
    DESCRIPCION                   VARCHAR(255),
    MONTO                         DECIMAL(10,2) NOT NULL,
    ID_TIPO_MOVIMIENTO_FINANCIERO INT NOT NULL,
    ID_VENTA                      INT,
    ID_EMPLEADO                   INT NOT NULL,
    ID_ESTADO                     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MOVIMIENTO_FINANCIERO_TB PRIMARY KEY (ID_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_TIPO FOREIGN KEY (ID_TIPO_MOVIMIENTO_FINANCIERO) REFERENCES PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB(ID_TIPO_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CAJA_TB (
    ID_CAJA        INT IDENTITY(1,1) NOT NULL,
    FECHA_APERTURA DATE NOT NULL DEFAULT GETDATE(),
    MONTO_INICIAL  DECIMAL(10,2) NOT NULL DEFAULT 0,
    FECHA_CIERRE   DATE,
    MONTO_FINAL    DECIMAL(10,2),
    DIFERENCIA     DECIMAL(10,2),
    ID_EMPLEADO    INT NOT NULL,
    ID_ESTADO      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CAJA_TB PRIMARY KEY (ID_CAJA),
    CONSTRAINT CK_PUBROCK_CAJA_MONTO_INICIAL CHECK (MONTO_INICIAL >= 0),
    CONSTRAINT FK_PUBROCK_CAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_CAJA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CIERRE_CAJA_TB (
    ID_CIERRE_CAJA  INT IDENTITY(1,1) NOT NULL,
    FECHA_CIERRE    DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_VENTAS    DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL_INGRESOS  DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL_EGRESOS   DECIMAL(10,2) NOT NULL DEFAULT 0,
    BALANCE_FINAL   DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_EMPLEADO     INT NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CIERRE_CAJA_TB PRIMARY KEY (ID_CIERRE_CAJA),
    CONSTRAINT FK_PUBROCK_CIERRE_CAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_CIERRE_CAJA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_BITACORA_TB (
    ID_BITACORA       INT IDENTITY(1,1) NOT NULL,
    FECHA_HORA        DATETIME NOT NULL DEFAULT GETDATE(),
    ACCION_REALIZADA  VARCHAR(255) NOT NULL,
    DESCRIPCION       VARCHAR(500),
    CEDULA            VARCHAR(20),
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_BITACORA_TB PRIMARY KEY (ID_BITACORA),
    CONSTRAINT FK_PUBROCK_BITACORA_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_BITACORA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 12: IMPUESTOS
-- =====================================================================
CREATE TABLE PUBROCK_IMPUESTO_TB (
    ID_IMPUESTO     INT IDENTITY(1,1) NOT NULL,
    NOMBRE_IMPUESTO VARCHAR(100) NOT NULL,
    PORCENTAJE      DECIMAL(5,2) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_IMPUESTO_TB PRIMARY KEY (ID_IMPUESTO),
    CONSTRAINT CK_PUBROCK_IMPUESTO_PORCENTAJE CHECK (PORCENTAJE BETWEEN 0 AND 100),
    CONSTRAINT FK_PUBROCK_IMPUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_VENTA_IMPUESTO_TB (
    ID_VENTA        INT NOT NULL,
    ID_IMPUESTO     INT NOT NULL,
    MONTO_IMPUESTO  DECIMAL(10,2) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_VENTA_IMPUESTO_TB PRIMARY KEY (ID_VENTA, ID_IMPUESTO),
    CONSTRAINT CK_PUBROCK_VENTA_IMPUESTO_MONTO CHECK (MONTO_IMPUESTO >= 0),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_IMPUESTO FOREIGN KEY (ID_IMPUESTO) REFERENCES PUBROCK_IMPUESTO_TB(ID_IMPUESTO),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 13: PROMOCIONES
-- =====================================================================
CREATE TABLE PUBROCK_PROMOCION_TB (
    ID_PROMOCION          INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PROMOCION      VARCHAR(100) NOT NULL,
    DESCRIPCION           VARCHAR(255),
    PORCENTAJE_DESCUENTO  DECIMAL(5,2) NOT NULL,
    FECHA_INICIO          DATE NOT NULL,
    FECHA_FIN             DATE NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROMOCION_TB PRIMARY KEY (ID_PROMOCION),
    CONSTRAINT CK_PUBROCK_PROMOCION_PORCENTAJE CHECK (PORCENTAJE_DESCUENTO BETWEEN 0 AND 100),
    CONSTRAINT CK_PUBROCK_PROMOCION_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_PROMOCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROMOCION_PRODUCTO_TB (
    ID_PROMOCION INT NOT NULL,
    ID_PRODUCTO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROMOCION_PRODUCTO_TB PRIMARY KEY (ID_PROMOCION, ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES PUBROCK_PROMOCION_TB(ID_PROMOCION),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 14: REPORTES
-- =====================================================================
CREATE TABLE PUBROCK_FORMATO_REPORTE_TB (
    ID_FORMATO_REPORTE INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_FORMATO_REPORTE_TB PRIMARY KEY (ID_FORMATO_REPORTE),
    CONSTRAINT FK_PUBROCK_FORMATO_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TIPO_REPORTE_TB (
    ID_TIPO_REPORTE INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION      VARCHAR(100) NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_REPORTE_TB PRIMARY KEY (ID_TIPO_REPORTE),
    CONSTRAINT FK_PUBROCK_TIPO_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_REPORTE_TB (
    ID_REPORTE          INT IDENTITY(1,1) NOT NULL,
    FECHA_GENERACION    DATE NOT NULL DEFAULT GETDATE(),
    FECHA_INICIO        DATE NOT NULL,
    FECHA_FIN           DATE NOT NULL,
    ID_TIPO_REPORTE     INT NOT NULL,
    ID_EMPLEADO         INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    ID_FORMATO_REPORTE  INT NOT NULL,
    CONSTRAINT PK_PUBROCK_REPORTE_TB PRIMARY KEY (ID_REPORTE),
    CONSTRAINT CK_PUBROCK_REPORTE_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_REPORTE_TIPO_REPORTE FOREIGN KEY (ID_TIPO_REPORTE) REFERENCES PUBROCK_TIPO_REPORTE_TB(ID_TIPO_REPORTE),
    CONSTRAINT FK_PUBROCK_REPORTE_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO),
    CONSTRAINT FK_PUBROCK_REPORTE_FORMATO FOREIGN KEY (ID_FORMATO_REPORTE) REFERENCES PUBROCK_FORMATO_REPORTE_TB(ID_FORMATO_REPORTE)
);
GO


-- =====================================================================
-- SECCION 15: CONTENIDO DE MARKETING
-- =====================================================================
CREATE TABLE PUBROCK_MARKETING_TB (
    ID_PUBLICACION   INT IDENTITY(1,1) NOT NULL,
    TITULO           VARCHAR(150) NOT NULL,
    TIPO_CONTENIDO   VARCHAR(50) NOT NULL,
    DESCRIPCION      VARCHAR(500) NOT NULL,
    FECHA_INICIO     DATE NOT NULL,
    FECHA_FIN        DATE NOT NULL,
    PRECIO           DECIMAL(10,2) NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    FECHA_REGISTRO   DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_PUBROCK_MARKETING_TB PRIMARY KEY (ID_PUBLICACION),
    CONSTRAINT CK_PUBROCK_MARKETING_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_MARKETING_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 16: MESAS Y RESERVACIONES
-- =====================================================================
CREATE TABLE PUBROCK_MESA_TB (
    ID_MESA     INT IDENTITY(1,1) NOT NULL,
    NUMERO_MESA INT NOT NULL,
    CAPACIDAD   INT NOT NULL,
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MESA_TB PRIMARY KEY (ID_MESA),
    CONSTRAINT UQ_PUBROCK_MESA_NUMERO UNIQUE (NUMERO_MESA),
    CONSTRAINT CK_PUBROCK_MESA_CAPACIDAD CHECK (CAPACIDAD > 0),
    CONSTRAINT FK_PUBROCK_MESA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_RESERVACION_TB (
    ID_RESERVACION      INT IDENTITY(1,1) NOT NULL,
    FECHA_RESERVACION   DATE NOT NULL,
    HORA_INICIO         TIME NOT NULL,
    HORA_FIN            TIME NOT NULL,
    CANTIDAD_PERSONAS   INT NOT NULL,
    OBSERVACIONES       VARCHAR(500),
    ID_CLIENTE          INT NOT NULL,
    ID_MESA             INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_RESERVACION_TB PRIMARY KEY (ID_RESERVACION),
    CONSTRAINT CK_PUBROCK_RESERVACION_PERSONAS CHECK (CANTIDAD_PERSONAS > 0),
    CONSTRAINT CK_PUBROCK_RESERVACION_HORAS CHECK (HORA_FIN > HORA_INICIO),
    CONSTRAINT FK_PUBROCK_RESERVACION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_RESERVACION_MESA FOREIGN KEY (ID_MESA) REFERENCES PUBROCK_MESA_TB(ID_MESA),
    CONSTRAINT FK_PUBROCK_RESERVACION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_HORARIO_TB (
    ID_HORARIO    INT IDENTITY(1,1) NOT NULL,
    DIA_SEMANA    VARCHAR(50) NOT NULL,
    HORA_ENTRADA  TIME NOT NULL,
    HORA_SALIDA   TIME NOT NULL,
    ID_EMPLEADO   INT NOT NULL,
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_HORARIO_TB PRIMARY KEY (ID_HORARIO),
    CONSTRAINT CK_PUBROCK_HORARIO_HORAS CHECK (HORA_SALIDA > HORA_ENTRADA),
    CONSTRAINT FK_PUBROCK_HORARIO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_HORARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 17: ORDENES
-- =====================================================================
CREATE TABLE PUBROCK_ESTADO_ORDEN_TB (
    ID_ESTADO_ORDEN INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION      VARCHAR(100) NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ESTADO_ORDEN_TB PRIMARY KEY (ID_ESTADO_ORDEN),
    CONSTRAINT FK_PUBROCK_ESTADO_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_ORDEN_TB (
    ID_ORDEN        INT IDENTITY(1,1) NOT NULL,
    FECHA_ORDEN     DATE NOT NULL DEFAULT GETDATE(),
    OBSERVACIONES   VARCHAR(500),
    ID_VENTA        INT NOT NULL,
    ID_ESTADO_ORDEN INT NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ORDEN_TB PRIMARY KEY (ID_ORDEN),
    CONSTRAINT FK_PUBROCK_ORDEN_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_ORDEN_ESTADO_ORDEN FOREIGN KEY (ID_ESTADO_ORDEN) REFERENCES PUBROCK_ESTADO_ORDEN_TB(ID_ESTADO_ORDEN),
    CONSTRAINT FK_PUBROCK_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_ORDEN_TB (
    ID_ORDEN     INT NOT NULL,
    ID_PRODUCTO  INT NOT NULL,
    CANTIDAD     INT NOT NULL,
    OBSERVACION  VARCHAR(255),
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_ORDEN_TB PRIMARY KEY (ID_ORDEN, ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_DETALLE_ORDEN_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES PUBROCK_ORDEN_TB(ID_ORDEN),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 18: INDICES DE APOYO SOBRE LLAVES FORANEAS
-- SQL Server NO crea automaticamente un indice sobre las columnas FK
-- (solo sobre la PK referenciada). Sin estos indices, los JOIN y los
-- borrados/actualizaciones en cascada logica recorren la tabla
-- completa. Se agregan sobre las columnas mas consultadas por un
-- sistema de punto de venta / restaurante.
-- =====================================================================
CREATE INDEX IX_PUBROCK_PROVINCIA_PAIS               ON PUBROCK_PROVINCIA_TB(ID_PAIS);
CREATE INDEX IX_PUBROCK_CANTON_PROVINCIA              ON PUBROCK_CANTON_TB(ID_PROVINCIA);
CREATE INDEX IX_PUBROCK_DISTRITO_CANTON               ON PUBROCK_DISTRITO_TB(ID_CANTON);
CREATE INDEX IX_PUBROCK_USUARIO_TIPO_USUARIO          ON PUBROCK_USUARIO_TB(ID_TIPO_USUARIO);
CREATE INDEX IX_PUBROCK_DIRECCION_PAIS                ON PUBROCK_DIRECCION_TB(ID_PAIS);
CREATE INDEX IX_PUBROCK_DIRECCION_PROVINCIA           ON PUBROCK_DIRECCION_TB(ID_PROVINCIA);
CREATE INDEX IX_PUBROCK_DIRECCION_CANTON              ON PUBROCK_DIRECCION_TB(ID_CANTON);
CREATE INDEX IX_PUBROCK_DIRECCION_DISTRITO            ON PUBROCK_DIRECCION_TB(ID_DISTRITO);
CREATE INDEX IX_PUBROCK_EMPLEADO_PUESTO               ON PUBROCK_EMPLEADO_TB(ID_PUESTO);
CREATE INDEX IX_PUBROCK_USUARIO_SISTEMA_EMPLEADO      ON PUBROCK_USUARIO_SISTEMA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_USUARIO_SISTEMA_ROL           ON PUBROCK_USUARIO_SISTEMA_TB(ID_ROL);
CREATE INDEX IX_PUBROCK_REGISTRO_ACTIVIDAD_USUARIO    ON PUBROCK_REGISTRO_ACTIVIDAD_TB(ID_USUARIO_SISTEMA);
CREATE INDEX IX_PUBROCK_PRODUCTO_CATEGORIA            ON PUBROCK_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO);
CREATE INDEX IX_PUBROCK_PRODUCTO_PROVEEDOR            ON PUBROCK_PRODUCTO_TB(ID_PROVEEDOR);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_INVENTARIO_INVENT  ON PUBROCK_MOVIMIENTO_INVENTARIO_TB(ID_INVENTARIO);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_INVENTARIO_TIPO    ON PUBROCK_MOVIMIENTO_INVENTARIO_TB(ID_TIPO_MOVIMIENTO);
CREATE INDEX IX_PUBROCK_COMPRA_PROVEEDOR              ON PUBROCK_COMPRA_TB(ID_PROVEEDOR);
CREATE INDEX IX_PUBROCK_COMPRA_EMPLEADO               ON PUBROCK_COMPRA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_COMPRA_COMPRA         ON PUBROCK_DETALLE_COMPRA_TB(ID_COMPRA);
CREATE INDEX IX_PUBROCK_DETALLE_COMPRA_PRODUCTO       ON PUBROCK_DETALLE_COMPRA_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_VENTA_CLIENTE                 ON PUBROCK_VENTA_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_VENTA_EMPLEADO                ON PUBROCK_VENTA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_VENTA_VENTA           ON PUBROCK_DETALLE_VENTA_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_DETALLE_VENTA_PRODUCTO        ON PUBROCK_DETALLE_VENTA_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_FACTURA_VENTA                 ON PUBROCK_FACTURA_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_FACTURA_TIPO_PAGO             ON PUBROCK_FACTURA_TB(ID_TIPO_PAGO);
CREATE INDEX IX_PUBROCK_DEVOLUCION_VENTA              ON PUBROCK_DEVOLUCION_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_DEVOLUCION_CLIENTE            ON PUBROCK_DEVOLUCION_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_DEVOLUCION_EMPLEADO           ON PUBROCK_DEVOLUCION_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_DEVOLUCION_DEVOLUCION ON PUBROCK_DETALLE_DEVOLUCION_TB(ID_DEVOLUCION);
CREATE INDEX IX_PUBROCK_DETALLE_DEVOLUCION_PRODUCTO   ON PUBROCK_DETALLE_DEVOLUCION_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_FINANCIERO_VENTA   ON PUBROCK_MOVIMIENTO_FINANCIERO_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_FINANCIERO_EMPLEADO ON PUBROCK_MOVIMIENTO_FINANCIERO_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_CAJA_EMPLEADO                 ON PUBROCK_CAJA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_CIERRE_CAJA_EMPLEADO          ON PUBROCK_CIERRE_CAJA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_BITACORA_CEDULA               ON PUBROCK_BITACORA_TB(CEDULA);
CREATE INDEX IX_PUBROCK_VENTA_IMPUESTO_IMPUESTO       ON PUBROCK_VENTA_IMPUESTO_TB(ID_IMPUESTO);
CREATE INDEX IX_PUBROCK_PROMOCION_PRODUCTO_PRODUCTO   ON PUBROCK_PROMOCION_PRODUCTO_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_REPORTE_TIPO_REPORTE          ON PUBROCK_REPORTE_TB(ID_TIPO_REPORTE);
CREATE INDEX IX_PUBROCK_REPORTE_EMPLEADO              ON PUBROCK_REPORTE_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_REPORTE_FORMATO               ON PUBROCK_REPORTE_TB(ID_FORMATO_REPORTE);
CREATE INDEX IX_PUBROCK_RESERVACION_CLIENTE           ON PUBROCK_RESERVACION_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_RESERVACION_MESA              ON PUBROCK_RESERVACION_TB(ID_MESA);
CREATE INDEX IX_PUBROCK_HORARIO_EMPLEADO              ON PUBROCK_HORARIO_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_ORDEN_VENTA                   ON PUBROCK_ORDEN_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_ORDEN_ESTADO_ORDEN            ON PUBROCK_ORDEN_TB(ID_ESTADO_ORDEN);
CREATE INDEX IX_PUBROCK_DETALLE_ORDEN_PRODUCTO        ON PUBROCK_DETALLE_ORDEN_TB(ID_PRODUCTO);
GO


-- =====================================================================
-- SECCION 19: MODULO DE VENTAS (GPV-001 a GPV-006)
-- Migracion ADITIVA: no se elimina ni renombra ninguna columna
-- existente de PUBROCK_VENTA_TB. Se agrega un catalogo de estados de
-- negocio propio de la venta (Pendiente/Pagada/Anulada), separado del
-- ID_ESTADO generico de borrado logico (Activo/Inactivo), y las
-- columnas de auditoria de anulacion.
-- =====================================================================
CREATE TABLE PUBROCK_ESTADO_VENTA_TB (
    ID_ESTADO_VENTA INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION     VARCHAR(50) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ESTADO_VENTA_TB PRIMARY KEY (ID_ESTADO_VENTA),
    CONSTRAINT UQ_PUBROCK_ESTADO_VENTA_DESCRIPCION UNIQUE (DESCRIPCION),
    CONSTRAINT FK_PUBROCK_ESTADO_VENTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

INSERT INTO PUBROCK_ESTADO_VENTA_TB (DESCRIPCION) VALUES
('Pendiente'),
('Pagada'),
('Anulada');
GO

ALTER TABLE PUBROCK_VENTA_TB ADD ID_ESTADO_VENTA INT NULL;
GO

UPDATE PUBROCK_VENTA_TB
SET ID_ESTADO_VENTA = (SELECT ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Pendiente')
WHERE ID_ESTADO_VENTA IS NULL;
GO

ALTER TABLE PUBROCK_VENTA_TB ALTER COLUMN ID_ESTADO_VENTA INT NOT NULL;
GO

ALTER TABLE PUBROCK_VENTA_TB ADD
    CONSTRAINT FK_PUBROCK_VENTA_ESTADO_VENTA FOREIGN KEY (ID_ESTADO_VENTA) REFERENCES PUBROCK_ESTADO_VENTA_TB(ID_ESTADO_VENTA);
GO

DECLARE @SqlDefaultEstadoVenta NVARCHAR(MAX) = N'
ALTER TABLE PUBROCK_VENTA_TB ADD CONSTRAINT DF_PUBROCK_VENTA_ESTADO_VENTA
    DEFAULT (' + CAST((SELECT ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Pendiente') AS NVARCHAR(20)) + N') FOR ID_ESTADO_VENTA;';
EXEC sp_executesql @SqlDefaultEstadoVenta;
GO

ALTER TABLE PUBROCK_VENTA_TB ADD
    FECHA_ANULACION  DATETIME NULL,
    MOTIVO_ANULACION VARCHAR(255) NULL;
GO

CREATE INDEX IX_PUBROCK_VENTA_ESTADO_VENTA ON PUBROCK_VENTA_TB(ID_ESTADO_VENTA);
GO

-- Tipos de movimiento de inventario necesarios para el flujo de ventas
-- (se insertan solo si no existen, para no duplicar catalogos ya
-- cargados por otros modulos).
IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB WHERE DESCRIPCION = 'Salida por Venta')
    INSERT INTO PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB (DESCRIPCION) VALUES ('Salida por Venta');
GO
GO

IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB WHERE DESCRIPCION = 'Entrada por Anulacion')
    INSERT INTO PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB (DESCRIPCION) VALUES ('Entrada por Anulacion');
GO

-- Tipo de tabla usada para enviar el detalle de productos/cantidades
-- de una venta al procedimiento de registro (evita SQL embebido con
-- listas concatenadas y permite validar todo en un solo set-based op).
IF TYPE_ID(N'PUBROCK_DETALLE_VENTA_TIPO_TB') IS NULL
    EXEC('CREATE TYPE PUBROCK_DETALLE_VENTA_TIPO_TB AS TABLE
    (
        ID_PRODUCTO INT NOT NULL,
        CANTIDAD    INT NOT NULL
    )');
GO


-- =====================================================================
-- SECCION 20: STORED PROCEDURES DEL MODULO DE VENTAS
-- =====================================================================

-- GPV-001: Registrar una venta (no descuenta inventario todavia).
-- @RESULTADO: 1 = OK | -1 producto no existe/inactivo | -2 cantidad
-- invalida | -3 stock insuficiente | -4 sin productos | -99 error.
IF OBJECT_ID('SP_PUBROCK_REGISTRAR_VENTA', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_REGISTRAR_VENTA;
GO

CREATE PROCEDURE SP_PUBROCK_REGISTRAR_VENTA
    @ID_EMPLEADO INT,
    @ID_CLIENTE  INT = NULL,
    @DETALLE     PUBROCK_DETALLE_VENTA_TIPO_TB READONLY,
    @ID_VENTA    INT OUTPUT,
    @RESULTADO   INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    SET @ID_VENTA = NULL;
    SET @RESULTADO = 0;

    IF NOT EXISTS (SELECT 1 FROM @DETALLE)
    BEGIN
        SET @RESULTADO = -4;
        RETURN;
    END

    IF EXISTS (SELECT 1 FROM @DETALLE WHERE CANTIDAD <= 0)
    BEGIN
        SET @RESULTADO = -2;
        RETURN;
    END

    IF EXISTS (
        SELECT 1 FROM @DETALLE D
        LEFT JOIN PUBROCK_PRODUCTO_TB P ON P.ID_PRODUCTO = D.ID_PRODUCTO AND P.ID_ESTADO = 1
        WHERE P.ID_PRODUCTO IS NULL
    )
    BEGIN
        SET @RESULTADO = -1;
        RETURN;
    END

    IF EXISTS (
        SELECT 1 FROM @DETALLE D
        INNER JOIN PUBROCK_INVENTARIO_TB I ON I.ID_PRODUCTO = D.ID_PRODUCTO
        WHERE I.STOCK_ACTUAL < D.CANTIDAD
    )
    BEGIN
        SET @RESULTADO = -3;
        RETURN;
    END

    DECLARE @ID_ESTADO_PENDIENTE INT = (SELECT TOP 1 ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Pendiente');
    DECLARE @ID_IMPUESTO INT = (SELECT TOP 1 ID_IMPUESTO FROM PUBROCK_IMPUESTO_TB WHERE ID_ESTADO = 1 ORDER BY ID_IMPUESTO);
    DECLARE @PORCENTAJE_IMPUESTO DECIMAL(5,2) = (SELECT PORCENTAJE FROM PUBROCK_IMPUESTO_TB WHERE ID_IMPUESTO = @ID_IMPUESTO);

    BEGIN TRAN;
    BEGIN TRY
        INSERT INTO PUBROCK_VENTA_TB (FECHA_VENTA, TOTAL_VENTA, ID_CLIENTE, ID_EMPLEADO, ID_ESTADO, ID_ESTADO_VENTA)
        VALUES (GETDATE(), 0, @ID_CLIENTE, @ID_EMPLEADO, 1, @ID_ESTADO_PENDIENTE);

        SET @ID_VENTA = SCOPE_IDENTITY();

        INSERT INTO PUBROCK_DETALLE_VENTA_TB (CANTIDAD, PRECIO_UNITARIO, SUBTOTAL, ID_VENTA, ID_PRODUCTO, ID_ESTADO)
        SELECT D.CANTIDAD, P.PRECIO_VENTA, D.CANTIDAD * P.PRECIO_VENTA, @ID_VENTA, D.ID_PRODUCTO, 1
        FROM @DETALLE D
        INNER JOIN PUBROCK_PRODUCTO_TB P ON P.ID_PRODUCTO = D.ID_PRODUCTO;

        DECLARE @SUBTOTAL_GENERAL DECIMAL(10,2) = (SELECT SUM(SUBTOTAL) FROM PUBROCK_DETALLE_VENTA_TB WHERE ID_VENTA = @ID_VENTA);
        DECLARE @MONTO_IMPUESTO DECIMAL(10,2) = ISNULL(@SUBTOTAL_GENERAL * (@PORCENTAJE_IMPUESTO / 100.0), 0);
        DECLARE @TOTAL DECIMAL(10,2) = @SUBTOTAL_GENERAL + @MONTO_IMPUESTO;

        UPDATE PUBROCK_VENTA_TB SET TOTAL_VENTA = @TOTAL WHERE ID_VENTA = @ID_VENTA;

        IF @ID_IMPUESTO IS NOT NULL AND @MONTO_IMPUESTO > 0
        BEGIN
            INSERT INTO PUBROCK_VENTA_IMPUESTO_TB (ID_VENTA, ID_IMPUESTO, MONTO_IMPUESTO, ID_ESTADO)
            VALUES (@ID_VENTA, @ID_IMPUESTO, @MONTO_IMPUESTO, 1);
        END

        COMMIT TRAN;
        SET @RESULTADO = 1;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRAN;
        SET @RESULTADO = -99;
        SET @ID_VENTA = NULL;
    END CATCH
END
GO

-- GPV-002 / GPV-006: Procesar el pago de una venta: valida, descuenta
-- inventario (nunca permite stock negativo) y genera el comprobante
-- (factura), todo dentro de una unica transaccion con rollback ante
-- cualquier error.
-- @RESULTADO: 1 = OK | -1 no existe | -2 ya pagada | -3 anulada |
-- -4 sin productos | -5 stock insuficiente | -99 error.
IF OBJECT_ID('SP_PUBROCK_PROCESAR_VENTA', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_PROCESAR_VENTA;
GO

CREATE PROCEDURE SP_PUBROCK_PROCESAR_VENTA
    @ID_VENTA     INT,
    @ID_TIPO_PAGO INT,
    @ID_FACTURA   INT OUTPUT,
    @RESULTADO    INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @RESULTADO = 0;
    SET @ID_FACTURA = NULL;

    DECLARE @ID_ESTADO_PAGADA INT = (SELECT TOP 1 ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Pagada');
    DECLARE @ID_ESTADO_ANULADA INT = (SELECT TOP 1 ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Anulada');
    DECLARE @ID_TIPO_MOV_SALIDA INT = (SELECT TOP 1 ID_TIPO_MOVIMIENTO FROM PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB WHERE DESCRIPCION = 'Salida por Venta' ORDER BY ID_TIPO_MOVIMIENTO);

    DECLARE @ESTADO_ACTUAL INT;
    SELECT @ESTADO_ACTUAL = ID_ESTADO_VENTA FROM PUBROCK_VENTA_TB WHERE ID_VENTA = @ID_VENTA AND ID_ESTADO = 1;

    IF @ESTADO_ACTUAL IS NULL
    BEGIN
        SET @RESULTADO = -1;
        RETURN;
    END

    IF @ESTADO_ACTUAL = @ID_ESTADO_PAGADA
    BEGIN
        SET @RESULTADO = -2;
        RETURN;
    END

    IF @ESTADO_ACTUAL = @ID_ESTADO_ANULADA
    BEGIN
        SET @RESULTADO = -3;
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM PUBROCK_DETALLE_VENTA_TB WHERE ID_VENTA = @ID_VENTA AND ID_ESTADO = 1)
    BEGIN
        SET @RESULTADO = -4;
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM PUBROCK_DETALLE_VENTA_TB DV
        INNER JOIN PUBROCK_INVENTARIO_TB I ON I.ID_PRODUCTO = DV.ID_PRODUCTO
        WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1
          AND I.STOCK_ACTUAL < DV.CANTIDAD
    )
    BEGIN
        SET @RESULTADO = -5;
        RETURN;
    END

    BEGIN TRAN;
    BEGIN TRY
        UPDATE I
        SET I.STOCK_ACTUAL = I.STOCK_ACTUAL - DV.CANTIDAD,
            I.FECHA_ULTIMA_ACTUALIZACION = GETDATE()
        FROM PUBROCK_INVENTARIO_TB I
        INNER JOIN PUBROCK_DETALLE_VENTA_TB DV ON DV.ID_PRODUCTO = I.ID_PRODUCTO
        WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1;

        IF EXISTS (SELECT 1 FROM PUBROCK_INVENTARIO_TB WHERE STOCK_ACTUAL < 0)
        BEGIN
            RAISERROR('Stock insuficiente durante el procesamiento de la venta', 16, 1);
        END

        INSERT INTO PUBROCK_MOVIMIENTO_INVENTARIO_TB (FECHA_MOVIMIENTO, CANTIDAD, OBSERVACION, ID_INVENTARIO, ID_TIPO_MOVIMIENTO, ID_ESTADO)
        SELECT GETDATE(), -DV.CANTIDAD, 'Descuento por venta #' + CAST(@ID_VENTA AS VARCHAR(20)), I.ID_INVENTARIO, @ID_TIPO_MOV_SALIDA, 1
        FROM PUBROCK_DETALLE_VENTA_TB DV
        INNER JOIN PUBROCK_INVENTARIO_TB I ON I.ID_PRODUCTO = DV.ID_PRODUCTO
        WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1;

        UPDATE PUBROCK_VENTA_TB SET ID_ESTADO_VENTA = @ID_ESTADO_PAGADA WHERE ID_VENTA = @ID_VENTA;

        DECLARE @MONTO_TOTAL DECIMAL(10,2) = (SELECT TOTAL_VENTA FROM PUBROCK_VENTA_TB WHERE ID_VENTA = @ID_VENTA);
        DECLARE @NUMERO_FACTURA VARCHAR(100) = 'FAC-' + CAST(@ID_VENTA AS VARCHAR(20)) + '-' + CONVERT(VARCHAR(8), GETDATE(), 112);

        INSERT INTO PUBROCK_FACTURA_TB (NUMERO_FACTURA, FECHA_FACTURA, MONTO_TOTAL, ID_VENTA, ID_TIPO_PAGO, ID_ESTADO)
        VALUES (@NUMERO_FACTURA, GETDATE(), @MONTO_TOTAL, @ID_VENTA, @ID_TIPO_PAGO, 1);

        SET @ID_FACTURA = SCOPE_IDENTITY();

        COMMIT TRAN;
        SET @RESULTADO = 1;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRAN;
        SET @RESULTADO = -99;
        SET @ID_FACTURA = NULL;
    END CATCH
END
GO

-- GPV-003 / GPV-006: Anular una venta (borrado logico por estado).
-- Si estaba Pagada, restaura el inventario dentro de la misma
-- transaccion. Nunca elimina registros fisicos.
-- @RESULTADO: 1 = OK | -1 no existe | -2 ya anulada | -99 error.
IF OBJECT_ID('SP_PUBROCK_ANULAR_VENTA', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_ANULAR_VENTA;
GO

CREATE PROCEDURE SP_PUBROCK_ANULAR_VENTA
    @ID_VENTA         INT,
    @MOTIVO_ANULACION VARCHAR(255) = NULL,
    @RESULTADO        INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;
    SET @RESULTADO = 0;

    DECLARE @ID_ESTADO_PAGADA  INT = (SELECT TOP 1 ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Pagada');
    DECLARE @ID_ESTADO_ANULADA INT = (SELECT TOP 1 ID_ESTADO_VENTA FROM PUBROCK_ESTADO_VENTA_TB WHERE DESCRIPCION = 'Anulada');
    DECLARE @ID_TIPO_MOV_ENTRADA INT = (SELECT TOP 1 ID_TIPO_MOVIMIENTO FROM PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB WHERE DESCRIPCION = 'Entrada por Anulacion' ORDER BY ID_TIPO_MOVIMIENTO);

    DECLARE @ESTADO_ACTUAL INT;
    SELECT @ESTADO_ACTUAL = ID_ESTADO_VENTA FROM PUBROCK_VENTA_TB WHERE ID_VENTA = @ID_VENTA AND ID_ESTADO = 1;

    IF @ESTADO_ACTUAL IS NULL
    BEGIN
        SET @RESULTADO = -1;
        RETURN;
    END

    IF @ESTADO_ACTUAL = @ID_ESTADO_ANULADA
    BEGIN
        SET @RESULTADO = -2;
        RETURN;
    END

    BEGIN TRAN;
    BEGIN TRY
        IF @ESTADO_ACTUAL = @ID_ESTADO_PAGADA
        BEGIN
            UPDATE I
            SET I.STOCK_ACTUAL = I.STOCK_ACTUAL + DV.CANTIDAD,
                I.FECHA_ULTIMA_ACTUALIZACION = GETDATE()
            FROM PUBROCK_INVENTARIO_TB I
            INNER JOIN PUBROCK_DETALLE_VENTA_TB DV ON DV.ID_PRODUCTO = I.ID_PRODUCTO
            WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1;

            INSERT INTO PUBROCK_MOVIMIENTO_INVENTARIO_TB (FECHA_MOVIMIENTO, CANTIDAD, OBSERVACION, ID_INVENTARIO, ID_TIPO_MOVIMIENTO, ID_ESTADO)
            SELECT GETDATE(), DV.CANTIDAD, 'Restitucion por anulacion de venta #' + CAST(@ID_VENTA AS VARCHAR(20)), I.ID_INVENTARIO, @ID_TIPO_MOV_ENTRADA, 1
            FROM PUBROCK_DETALLE_VENTA_TB DV
            INNER JOIN PUBROCK_INVENTARIO_TB I ON I.ID_PRODUCTO = DV.ID_PRODUCTO
            WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1;
        END

        UPDATE PUBROCK_VENTA_TB
        SET ID_ESTADO_VENTA  = @ID_ESTADO_ANULADA,
            FECHA_ANULACION  = GETDATE(),
            MOTIVO_ANULACION = @MOTIVO_ANULACION
        WHERE ID_VENTA = @ID_VENTA;

        COMMIT TRAN;
        SET @RESULTADO = 1;
    END TRY
    BEGIN CATCH
        IF XACT_STATE() <> 0 ROLLBACK TRAN;
        SET @RESULTADO = -99;
    END CATCH
END
GO

-- GPV-005: Detalle completo de una venta (cabecera + lineas). Se
-- devuelven dos result sets consumidos por el Repository con Dapper-
-- like mapping via SqlDataReader/EF.
IF OBJECT_ID('SP_PUBROCK_OBTENER_DETALLE_VENTA', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_OBTENER_DETALLE_VENTA;
GO

CREATE PROCEDURE SP_PUBROCK_OBTENER_DETALLE_VENTA
    @ID_VENTA INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        V.ID_VENTA         AS IdVenta,
        V.FECHA_VENTA      AS FechaVenta,
        V.ID_CLIENTE       AS IdCliente,
        V.ID_EMPLEADO      AS IdEmpleado,
        EV.DESCRIPCION     AS Estado,
        V.TOTAL_VENTA      AS Total,
        ISNULL((SELECT SUM(SUBTOTAL) FROM PUBROCK_DETALLE_VENTA_TB WHERE ID_VENTA = V.ID_VENTA AND ID_ESTADO = 1), 0) AS SubtotalGeneral,
        ISNULL((SELECT SUM(MONTO_IMPUESTO) FROM PUBROCK_VENTA_IMPUESTO_TB WHERE ID_VENTA = V.ID_VENTA AND ID_ESTADO = 1), 0) AS TotalImpuestos,
        V.FECHA_ANULACION  AS FechaAnulacion,
        V.MOTIVO_ANULACION AS MotivoAnulacion
    FROM PUBROCK_VENTA_TB V
    INNER JOIN PUBROCK_ESTADO_VENTA_TB EV ON EV.ID_ESTADO_VENTA = V.ID_ESTADO_VENTA
    WHERE V.ID_VENTA = @ID_VENTA;

    SELECT
        DV.ID_DETALLE_VENTA AS IdDetalleVenta,
        DV.ID_PRODUCTO      AS IdProducto,
        P.NOMBRE_PRODUCTO   AS NombreProducto,
        DV.CANTIDAD         AS Cantidad,
        DV.PRECIO_UNITARIO  AS PrecioUnitario,
        DV.SUBTOTAL         AS Subtotal
    FROM PUBROCK_DETALLE_VENTA_TB DV
    INNER JOIN PUBROCK_PRODUCTO_TB P ON P.ID_PRODUCTO = DV.ID_PRODUCTO
    WHERE DV.ID_VENTA = @ID_VENTA AND DV.ID_ESTADO = 1;
END
GO

-- GPV-004: Busqueda parcial de productos activos y con stock
-- disponible, por nombre, codigo de barras o categoria.
IF OBJECT_ID('SP_PUBROCK_BUSCAR_PRODUCTOS', 'P') IS NOT NULL
    DROP PROCEDURE SP_PUBROCK_BUSCAR_PRODUCTOS;
GO

CREATE PROCEDURE SP_PUBROCK_BUSCAR_PRODUCTOS
    @TEXTO_BUSQUEDA VARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        P.ID_PRODUCTO            AS IdProducto,
        P.CODIGO_BARRAS          AS Codigo,
        P.NOMBRE_PRODUCTO        AS Nombre,
        P.PRECIO_VENTA           AS Precio,
        ISNULL(I.STOCK_ACTUAL,0) AS StockDisponible,
        C.NOMBRE_CATEGORIA       AS Categoria
    FROM PUBROCK_PRODUCTO_TB P
    INNER JOIN PUBROCK_CATEGORIA_PRODUCTO_TB C ON C.ID_CATEGORIA_PRODUCTO = P.ID_CATEGORIA_PRODUCTO
    LEFT JOIN PUBROCK_INVENTARIO_TB I ON I.ID_PRODUCTO = P.ID_PRODUCTO
    WHERE P.ID_ESTADO = 1
      AND ISNULL(I.STOCK_ACTUAL,0) > 0
      AND (
            @TEXTO_BUSQUEDA IS NULL OR @TEXTO_BUSQUEDA = ''
            OR P.NOMBRE_PRODUCTO LIKE '%' + @TEXTO_BUSQUEDA + '%'
            OR P.CODIGO_BARRAS LIKE '%' + @TEXTO_BUSQUEDA + '%'
            OR C.NOMBRE_CATEGORIA LIKE '%' + @TEXTO_BUSQUEDA + '%'
      )
    ORDER BY P.NOMBRE_PRODUCTO;
END
GO

-- =====================================================================
-- SECCION 21: MODULO DE CONTABILIDAD (CON-001 a CON-006)
-- Extensiones aditivas: no se elimina ni renombra ninguna tabla,
-- columna o relacion existente. Solo se agregan columnas nuevas
-- (con DEFAULT para no romper filas existentes) y tablas nuevas
-- para soportar Egresos, Cierre de Caja, Balance, Cuentas por Pagar,
-- Impuestos y Bitacora Contable.
-- =====================================================================

-- 21.1 Egresos / Gastos operativos (CON-001): se reutiliza
-- PUBROCK_MOVIMIENTO_FINANCIERO_TB agregando la categoria del gasto
-- (Servicios, Insumos, Salarios, Mantenimiento, Otros) y la bandera
-- de "gasto fijo" solicitada en el Escenario 4.
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_MOVIMIENTO_FINANCIERO_TB') AND name = 'CATEGORIA')
BEGIN
    ALTER TABLE PUBROCK_MOVIMIENTO_FINANCIERO_TB ADD CATEGORIA VARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_MOVIMIENTO_FINANCIERO_TB') AND name = 'ES_FIJO')
BEGIN
    ALTER TABLE PUBROCK_MOVIMIENTO_FINANCIERO_TB ADD ES_FIJO BIT NOT NULL CONSTRAINT DF_PUBROCK_MOVIMIENTO_FINANCIERO_ES_FIJO DEFAULT (0);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_MOVIMIENTO_FINANCIERO_TB') AND name = 'NUMERO_COMPROBANTE')
BEGIN
    ALTER TABLE PUBROCK_MOVIMIENTO_FINANCIERO_TB ADD NUMERO_COMPROBANTE VARCHAR(50) NULL;
END
GO

-- Catalogo base de tipos de movimiento (Ingreso / Egreso), requerido
-- por PUBROCK_MOVIMIENTO_FINANCIERO_TB.ID_TIPO_MOVIMIENTO_FINANCIERO.
IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB WHERE DESCRIPCION = 'Ingreso')
BEGIN
    INSERT INTO PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (DESCRIPCION, ID_ESTADO) VALUES ('Ingreso', 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB WHERE DESCRIPCION = 'Egreso')
BEGIN
    INSERT INTO PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (DESCRIPCION, ID_ESTADO) VALUES ('Egreso', 1);
END
GO

-- 21.2 Cierre de Caja diario (CON-002): se agrega el monto contado
-- fisicamente para poder comparar contra el TOTAL_VENTAS del sistema
-- y dejar trazabilidad de quien realizo el cierre.
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_CIERRE_CAJA_TB') AND name = 'MONTO_CONTADO')
BEGIN
    ALTER TABLE PUBROCK_CIERRE_CAJA_TB ADD MONTO_CONTADO DECIMAL(10,2) NOT NULL CONSTRAINT DF_PUBROCK_CIERRE_CAJA_MONTO_CONTADO DEFAULT (0);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_CIERRE_CAJA_TB') AND name = 'CEDULA_REGISTRO')
BEGIN
    ALTER TABLE PUBROCK_CIERRE_CAJA_TB ADD CEDULA_REGISTRO VARCHAR(20) NULL;
    ALTER TABLE PUBROCK_CIERRE_CAJA_TB ADD CONSTRAINT FK_PUBROCK_CIERRE_CAJA_USUARIO FOREIGN KEY (CEDULA_REGISTRO) REFERENCES PUBROCK_USUARIO_TB(CEDULA);
END
GO

-- Un unico cierre "vigente" (ID_ESTADO = 1) por dia natural.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_PUBROCK_CIERRE_CAJA_FECHA_ACTIVO')
BEGIN
    CREATE UNIQUE INDEX UQ_PUBROCK_CIERRE_CAJA_FECHA_ACTIVO
        ON PUBROCK_CIERRE_CAJA_TB (FECHA_CIERRE)
        WHERE ID_ESTADO = 1;
END
GO

-- 21.3 Cuentas por Pagar a proveedores (CON-004).
IF OBJECT_ID('PUBROCK_CUENTA_POR_PAGAR_TB') IS NULL
BEGIN
    CREATE TABLE PUBROCK_CUENTA_POR_PAGAR_TB (
        ID_CUENTA_POR_PAGAR    INT IDENTITY(1,1) NOT NULL,
        PROVEEDOR              VARCHAR(150) NOT NULL,
        MONTO                  DECIMAL(10,2) NOT NULL,
        DESCRIPCION            VARCHAR(255) NOT NULL,
        FECHA_REGISTRO         DATE NOT NULL DEFAULT GETDATE(),
        FECHA_VENCIMIENTO      DATE NOT NULL,
        FECHA_PAGO             DATE NULL,
        ESTADO_PAGO            VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
        NOTIFICACION_ENVIADA   BIT NOT NULL DEFAULT 0,
        ID_MOVIMIENTO_FINANCIERO INT NULL,
        CEDULA_REGISTRO        VARCHAR(20) NULL,
        ID_ESTADO              INT NOT NULL DEFAULT 1,
        CONSTRAINT PK_PUBROCK_CUENTA_POR_PAGAR_TB PRIMARY KEY (ID_CUENTA_POR_PAGAR),
        CONSTRAINT CK_PUBROCK_CUENTA_POR_PAGAR_MONTO CHECK (MONTO > 0),
        CONSTRAINT CK_PUBROCK_CUENTA_POR_PAGAR_ESTADO_PAGO CHECK (ESTADO_PAGO IN ('Pendiente','Pagado')),
        CONSTRAINT FK_PUBROCK_CUENTA_POR_PAGAR_MOVIMIENTO FOREIGN KEY (ID_MOVIMIENTO_FINANCIERO) REFERENCES PUBROCK_MOVIMIENTO_FINANCIERO_TB(ID_MOVIMIENTO_FINANCIERO),
        CONSTRAINT FK_PUBROCK_CUENTA_POR_PAGAR_USUARIO FOREIGN KEY (CEDULA_REGISTRO) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
        CONSTRAINT FK_PUBROCK_CUENTA_POR_PAGAR_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
    );
END
GO

-- 21.4 Impuestos de ley (CON-005): tasas iniciales IVA 13% / Servicio 10%.
IF NOT EXISTS (SELECT 1 FROM PUBROCK_IMPUESTO_TB WHERE NOMBRE_IMPUESTO = 'IVA')
BEGIN
    INSERT INTO PUBROCK_IMPUESTO_TB (NOMBRE_IMPUESTO, PORCENTAJE, ID_ESTADO) VALUES ('IVA', 13.00, 1);
END
GO

IF NOT EXISTS (SELECT 1 FROM PUBROCK_IMPUESTO_TB WHERE NOMBRE_IMPUESTO = 'Servicio')
BEGIN
    INSERT INTO PUBROCK_IMPUESTO_TB (NOMBRE_IMPUESTO, PORCENTAJE, ID_ESTADO) VALUES ('Servicio', 10.00, 1);
END
GO

-- 21.5 Bitacora Contable (CON-006): se agrega el modulo/categoria del
-- evento para poder filtrar por "Contabilidad" tal como pide la
-- historia de usuario, sin afectar los registros ya guardados.
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('PUBROCK_BITACORA_TB') AND name = 'MODULO')
BEGIN
    ALTER TABLE PUBROCK_BITACORA_TB ADD MODULO VARCHAR(100) NULL;
END
GO

-- =====================================================================
-- FIN DEL SCRIPT
-- Se retiraron intencionalmente del final del script original los
-- siguientes comandos, por ser destructivos/peligrosos y no tener
-- ningun lugar en un script de creacion de base de datos:
--   ALTER DATABASE PUBROCK_CR SET EMERGENCY;
--   ALTER DATABASE PUBROCK_CR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--   DBCC CHECKDB(PUBROCK_CR, REPAIR_ALLOW_DATA_LOSS);
--   ALTER DATABASE PUBROCK_CR SET MULTI_USER;
-- Ver PUBROCK_REPORTE_CAMBIOS.md para el detalle completo.
-- =====================================================================
PRINT 'BASE DE DATOS PUBROCK_CR CREADA CORRECTAMENTE.';
GO



-- Script de Corrección para PUBROCK_CR
-- Ejecuta este script si el diagnóstico muestra que falta el tipo 'Egreso'

-- 1. Insertar el tipo de movimiento 'Egreso' si no existe
IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB WHERE DESCRIPCION = 'Egreso')
BEGIN
	INSERT INTO PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (DESCRIPCION, ID_ESTADO)
	VALUES ('Egreso', 1);
	SELECT 'Tipo Egreso insertado correctamente' AS [Resultado];
END
ELSE
BEGIN
	SELECT 'El tipo Egreso ya existe' AS [Resultado];
END

-- 2. Insertar el tipo de movimiento 'Ingreso' si no existe
IF NOT EXISTS (SELECT 1 FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB WHERE DESCRIPCION = 'Ingreso')
BEGIN
	INSERT INTO PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (DESCRIPCION, ID_ESTADO)
	VALUES ('Ingreso', 1);
	SELECT 'Tipo Ingreso insertado correctamente' AS [Resultado];
END
ELSE
BEGIN
	SELECT 'El tipo Ingreso ya existe' AS [Resultado];
END

-- 3. Verificar que los tipos fueron insertados
SELECT 
	ISNULL(ID_TIPO_MOVIMIENTO_FINANCIERO, 'N/A') AS [TipoID],
	DESCRIPCION,
	ID_ESTADO
FROM PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB
WHERE DESCRIPCION IN ('Egreso', 'Ingreso')
ORDER BY DESCRIPCION;
GO

-- =====================================================================
-- PROCEDIMIENTO: REPORTE DE VENTAS
-- Devuelve facturas/ventas con totales, impuestos y datos relacionados.
-- Parámetros opcionales para filtrar por fecha, categoría, tipo de pago, cliente o estado.
-- =====================================================================
CREATE PROCEDURE SP_PUBROCK_REPORTE_VENTAS
    @FechaInicio    DATE = NULL,
    @FechaFin       DATE = NULL,
    @IdCategoria    INT  = NULL,
    @IdTipoPago     INT  = NULL,
    @IdCliente      INT  = NULL,
    @IdEstado       INT  = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        f.NUMERO_FACTURA      AS NumeroFactura,
        f.FECHA_FACTURA       AS Fecha,
        ISNULL(u.NOMBRE + ' ' + u.APELLIDO_PATERNO, '') AS Cliente,
        ISNULL(usr.NOMBRE + ' ' + usr.APELLIDO_PATERNO, '') AS Usuario,
        tp.DESCRIPCION        AS MetodoPago,
        SUM(dv.SUBTOTAL)     AS Subtotal,
        ISNULL((SELECT SUM(vim.MONTO_IMPUESTO) FROM PUBROCK_VENTA_IMPUESTO_TB vim WHERE vim.ID_VENTA = v.ID_VENTA AND vim.ID_ESTADO = 1), 0) AS IVA,
        0.00                 AS Descuento,
        f.MONTO_TOTAL        AS Total,
        est.DESCRIPCION      AS Estado
    FROM PUBROCK_FACTURA_TB f
    INNER JOIN PUBROCK_VENTA_TB v ON f.ID_VENTA = v.ID_VENTA
    LEFT JOIN PUBROCK_DETALLE_VENTA_TB dv ON dv.ID_VENTA = v.ID_VENTA AND dv.ID_ESTADO = 1
    LEFT JOIN PUBROCK_TIPO_PAGO_TB tp ON f.ID_TIPO_PAGO = tp.ID_TIPO_PAGO
    LEFT JOIN PUBROCK_CLIENTE_TB c ON v.ID_CLIENTE = c.ID_CLIENTE
    LEFT JOIN PUBROCK_USUARIO_TB u ON c.CEDULA = u.CEDULA
    LEFT JOIN PUBROCK_EMPLEADO_TB e ON v.ID_EMPLEADO = e.ID_EMPLEADO
    LEFT JOIN PUBROCK_USUARIO_TB usr ON e.CEDULA = usr.CEDULA
    LEFT JOIN PUBROCK_ESTADO_TB est ON v.ID_ESTADO = est.ID_ESTADO
    LEFT JOIN PUBROCK_PRODUCTO_TB p ON dv.ID_PRODUCTO = p.ID_PRODUCTO
    WHERE (@FechaInicio IS NULL OR f.FECHA_FACTURA >= @FechaInicio)
      AND (@FechaFin IS NULL OR f.FECHA_FACTURA <= @FechaFin)
      AND (@IdCategoria IS NULL OR p.ID_CATEGORIA_PRODUCTO = @IdCategoria)
      AND (@IdTipoPago IS NULL OR f.ID_TIPO_PAGO = @IdTipoPago)
      AND (@IdCliente IS NULL OR v.ID_CLIENTE = @IdCliente)
      AND (@IdEstado IS NULL OR v.ID_ESTADO = @IdEstado)
    GROUP BY
        f.NUMERO_FACTURA,
        f.FECHA_FACTURA,
        u.NOMBRE, u.APELLIDO_PATERNO,
        usr.NOMBRE, usr.APELLIDO_PATERNO,
        tp.DESCRIPCION,
        f.MONTO_TOTAL,
        est.DESCRIPCION,
        v.ID_VENTA
    ORDER BY f.FECHA_FACTURA DESC;
END
GO
