/* =====================================================================
   PUBROCK_CR.sql
   Base de datos del sistema de administracion del restaurante PUBROCK
   Version revisada por: Arquitectura de Datos Senior
   Motor: SQL Server 2016+
   Compatibilidad: proyecto C# .NET Framework 4.8.1 (se conservan TODOS
   los nombres de tablas y columnas existentes)
   ===================================================================== */

-- =====================================================================
-- SECCION 0: CREACION DE LA BASE DE DATOS
-- =====================================================================
IF DB_ID('PUBROCK_CR') IS NOT NULL
BEGIN
    ALTER DATABASE PUBROCK_CR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PUBROCK_CR;
END;
GO

CREATE DATABASE PUBROCK_CR;
GO

USE PUBROCK_CR;
GO

-- Habilita a 'sa' como propietario de la base para evitar el error
-- "Error no especificado" al crear diagramas de base de datos en SSMS.
-- (Se conserva porque es inofensivo; se retiraron mas adelante todos
--  los comandos verdaderamente peligrosos del script original.)
ALTER AUTHORIZATION ON DATABASE::PUBROCK_CR TO sa;
GO


-- =====================================================================
-- SECCION 1: TABLA MAESTRA DE ESTADOS
-- Todas las tablas del sistema usan ID_ESTADO como bandera logica de
-- activo/inactivo (borrado logico). Se crea primero porque es
-- referenciada por practicamente todo el modelo.
-- =====================================================================
CREATE TABLE PUBROCK_ESTADO_TB (
    ID_ESTADO   INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PUBROCK_ESTADO_TB PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UQ_PUBROCK_ESTADO_DESCRIPCION UNIQUE (DESCRIPCION)
);
GO

-- Datos base indispensables: sin estos registros, cualquier INSERT
-- posterior que use ID_ESTADO = 1 fallaria por violacion de FK.
-- (En el script original esta carga faltaba por completo.)
INSERT INTO PUBROCK_ESTADO_TB (DESCRIPCION) VALUES
('Activo'),
('Inactivo');
GO


-- =====================================================================
-- SECCION 2: UBICACIONES GEOGRAFICAS (jerarquia Pais -> Provincia ->
-- Canton -> Distrito). Se agregan las relaciones jerarquicas faltantes
-- solicitadas (mejora de integridad referencial), sin eliminar ni
-- renombrar ninguna columna existente.
-- =====================================================================
CREATE TABLE PUBROCK_PAIS_TB (
    ID_PAIS   INT IDENTITY(1,1) NOT NULL,
    NOMBRE    VARCHAR(100) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PAIS_TB PRIMARY KEY (ID_PAIS),
    CONSTRAINT FK_PUBROCK_PAIS_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROVINCIA_TB (
    ID_PROVINCIA INT IDENTITY(1,1) NOT NULL,
    NOMBRE       VARCHAR(100) NOT NULL,
    ID_PAIS      INT NOT NULL,                 -- NUEVO: relacion jerarquica Provincia -> Pais
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROVINCIA_TB PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_PROVINCIA_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PUBROCK_PAIS_TB(ID_PAIS),
    CONSTRAINT FK_PUBROCK_PROVINCIA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CANTON_TB (
    ID_CANTON    INT IDENTITY(1,1) NOT NULL,
    NOMBRE       VARCHAR(100) NOT NULL,
    ID_PROVINCIA INT NOT NULL,                 -- NUEVO: relacion jerarquica Canton -> Provincia
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CANTON_TB PRIMARY KEY (ID_CANTON),
    CONSTRAINT FK_PUBROCK_CANTON_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PUBROCK_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_CANTON_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DISTRITO_TB (
    ID_DISTRITO INT IDENTITY(1,1) NOT NULL,
    NOMBRE      VARCHAR(100) NOT NULL,
    ID_CANTON   INT NOT NULL,                  -- NUEVO: relacion jerarquica Distrito -> Canton
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DISTRITO_TB PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT FK_PUBROCK_DISTRITO_CANTON FOREIGN KEY (ID_CANTON) REFERENCES PUBROCK_CANTON_TB(ID_CANTON),
    CONSTRAINT FK_PUBROCK_DISTRITO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 3: USUARIOS
-- NOTA DE DISENO: en el script original la tabla PUBROCK_USUARIO_TB se
-- creaba SIN las columnas CORREO, TELEFONO y CONTRASENIA, se insertaba
-- un registro que SI las usaba (error de ejecucion garantizado) y
-- recien despues se agregaban esas columnas con ALTER TABLE. Se corrige
-- unificando todas las columnas en el CREATE TABLE y moviendo el
-- INSERT despues de la definicion completa.
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_USUARIO_TB (
    ID_TIPO_USUARIO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION     VARCHAR(100) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_USUARIO_TB PRIMARY KEY (ID_TIPO_USUARIO),
    CONSTRAINT FK_PUBROCK_TIPO_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

INSERT INTO PUBROCK_TIPO_USUARIO_TB (DESCRIPCION, ID_ESTADO) VALUES
('Administrador', 1),
('Empleado', 1),
('Cliente', 1),
('Proveedor', 1);
GO

CREATE TABLE PUBROCK_USUARIO_TB (
    CEDULA            VARCHAR(20) NOT NULL,
    NOMBRE            VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO  VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO  VARCHAR(100),
    FECHA_REGISTRO    DATE NOT NULL DEFAULT GETDATE(),
    ID_TIPO_USUARIO   INT NOT NULL,
    CORREO            VARCHAR(100),
    TELEFONO          VARCHAR(20),
    CONTRASENIA       VARCHAR(255),
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_USUARIO_TB PRIMARY KEY (CEDULA),
    CONSTRAINT FK_PUBROCK_USUARIO_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES PUBROCK_TIPO_USUARIO_TB(ID_TIPO_USUARIO),
    CONSTRAINT FK_PUBROCK_USUARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

-- Indice unico "filtrado": permite muchos usuarios sin correo (NULL)
-- pero impide correos duplicados cuando si existen.
CREATE UNIQUE INDEX UQ_PUBROCK_USUARIO_CORREO ON PUBROCK_USUARIO_TB(CORREO) WHERE CORREO IS NOT NULL;
GO

INSERT INTO PUBROCK_USUARIO_TB
(
    CEDULA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO,
    FECHA_REGISTRO, ID_TIPO_USUARIO, CORREO, TELEFONO, CONTRASENIA, ID_ESTADO
)
VALUES
(
    '123456789', 'Administrador', 'Sistema', 'Principal',
    GETDATE(), 1, 'admin@pubrock.com', '88888888', 'Admin123', 1
);
GO

CREATE TABLE PUBROCK_DIRECCION_TB (
    CEDULA       VARCHAR(20) NOT NULL,
    ID_PAIS      INT,
    ID_PROVINCIA INT,
    ID_CANTON    INT,
    ID_DISTRITO  INT,
    OTRAS_SENAS  VARCHAR(500),
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DIRECCION_TB PRIMARY KEY (CEDULA),
    CONSTRAINT FK_PUBROCK_DIRECCION_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_DIRECCION_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PUBROCK_PAIS_TB(ID_PAIS),
    CONSTRAINT FK_PUBROCK_DIRECCION_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PUBROCK_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FK_PUBROCK_DIRECCION_CANTON FOREIGN KEY (ID_CANTON) REFERENCES PUBROCK_CANTON_TB(ID_CANTON),
    CONSTRAINT FK_PUBROCK_DIRECCION_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES PUBROCK_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FK_PUBROCK_DIRECCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TELEFONO_TB (
    CEDULA    VARCHAR(20) NOT NULL,
    TELEFONO  VARCHAR(20) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TELEFONO_TB PRIMARY KEY (CEDULA, TELEFONO),
    CONSTRAINT FK_PUBROCK_TELEFONO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_TELEFONO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CORREO_ELECTRONICO_TB (
    CEDULA    VARCHAR(20) NOT NULL,
    CORREO    VARCHAR(150) NOT NULL,
    ID_ESTADO INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CORREO_ELECTRONICO_TB PRIMARY KEY (CEDULA, CORREO),
    CONSTRAINT FK_PUBROCK_CORREO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_CORREO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 4: EMPLEADOS
-- NOTA DE DISENO (PK compuesta innecesaria): la tabla original definia
-- PRIMARY KEY (ID_EMPLEADO, CEDULA) y ADEMAS un UNIQUE(ID_EMPLEADO).
-- Si ID_EMPLEADO ya es unico por si solo, la PK compuesta no aporta
-- nada: cualquier busqueda por ID_EMPLEADO (la forma normal de
-- trabajar de una app .NET con Entity/ADO.NET) termina golpeando un
-- indice mas pesado de lo necesario, y la relacion 1 a 1 real con
-- CEDULA se expresa mejor como UNIQUE simple. Se corrige dejando
-- ID_EMPLEADO como PK y CEDULA como UNIQUE + FK. Mismo caso en
-- PUBROCK_PROVEEDOR_TB. Ninguna columna fue eliminada ni renombrada.
-- =====================================================================
CREATE TABLE PUBROCK_PUESTO_TB (
    ID_PUESTO     INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PUESTO VARCHAR(100) NOT NULL,
    DESCRIPCION   VARCHAR(255),
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PUESTO_TB PRIMARY KEY (ID_PUESTO),
    CONSTRAINT FK_PUBROCK_PUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_EMPLEADO_TB (
    ID_EMPLEADO   INT IDENTITY(1,1) NOT NULL,
    FECHA_INGRESO DATE NOT NULL DEFAULT GETDATE(),
    CEDULA        VARCHAR(20) NOT NULL,
    ID_PUESTO     INT NOT NULL,
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_EMPLEADO_TB PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT UQ_PUBROCK_EMPLEADO_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_EMPLEADO_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_EMPLEADO_PUESTO FOREIGN KEY (ID_PUESTO) REFERENCES PUBROCK_PUESTO_TB(ID_PUESTO),
    CONSTRAINT FK_PUBROCK_EMPLEADO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_ROL_TB (
    ID_ROL      INT IDENTITY(1,1) NOT NULL,
    NOMBRE_ROL  VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ROL_TB PRIMARY KEY (ID_ROL),
    CONSTRAINT FK_PUBROCK_ROL_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_USUARIO_SISTEMA_TB (
    ID_USUARIO_SISTEMA INT IDENTITY(1,1) NOT NULL,
    NOMBRE_USUARIO     VARCHAR(100) NOT NULL,
    CLAVE              VARCHAR(255) NOT NULL,
    FECHA_REGISTRO     DATE NOT NULL DEFAULT GETDATE(),
    ID_EMPLEADO        INT NOT NULL,
    ID_ROL             INT NOT NULL,
    ID_ESTADO          INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_USUARIO_SISTEMA_TB PRIMARY KEY (ID_USUARIO_SISTEMA),
    CONSTRAINT UQ_PUBROCK_USUARIO_SISTEMA_NOMBRE UNIQUE (NOMBRE_USUARIO),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_ROL FOREIGN KEY (ID_ROL) REFERENCES PUBROCK_ROL_TB(ID_ROL),
    CONSTRAINT FK_PUBROCK_USUARIO_SISTEMA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_REGISTRO_ACTIVIDAD_TB (
    ID_REGISTRO_ACTIVIDAD INT IDENTITY(1,1) NOT NULL,
    FECHA_HORA            DATETIME NOT NULL DEFAULT GETDATE(),
    ACCION_REALIZADA      VARCHAR(255) NOT NULL,
    DESCRIPCION           VARCHAR(500),
    ID_USUARIO_SISTEMA    INT NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_REGISTRO_ACTIVIDAD_TB PRIMARY KEY (ID_REGISTRO_ACTIVIDAD),
    CONSTRAINT FK_PUBROCK_REGISTRO_ACTIVIDAD_USUARIO_SISTEMA FOREIGN KEY (ID_USUARIO_SISTEMA) REFERENCES PUBROCK_USUARIO_SISTEMA_TB(ID_USUARIO_SISTEMA),
    CONSTRAINT FK_PUBROCK_REGISTRO_ACTIVIDAD_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 5: CLIENTES Y PROVEEDORES
-- =====================================================================
CREATE TABLE PUBROCK_CLIENTE_TB (
    ID_CLIENTE            INT IDENTITY(1,1) NOT NULL,
    FECHA_INGRESO_CLIENTE DATE NOT NULL DEFAULT GETDATE(),
    CEDULA                VARCHAR(20) NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CLIENTE_TB PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_PUBROCK_CLIENTE_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_CLIENTE_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_CLIENTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROVEEDOR_TB (
    ID_PROVEEDOR            INT IDENTITY(1,1) NOT NULL,
    CONTACTO_PRINCIPAL      VARCHAR(100),
    FECHA_INGRESO_PROVEEDOR DATE NOT NULL DEFAULT GETDATE(),
    CEDULA                  VARCHAR(20) NOT NULL,
    ID_ESTADO               INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROVEEDOR_TB PRIMARY KEY (ID_PROVEEDOR),
    CONSTRAINT UQ_PUBROCK_PROVEEDOR_CEDULA UNIQUE (CEDULA),
    CONSTRAINT FK_PUBROCK_PROVEEDOR_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_PROVEEDOR_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 6: PRODUCTOS E INVENTARIO
-- =====================================================================
CREATE TABLE PUBROCK_CATEGORIA_PRODUCTO_TB (
    ID_CATEGORIA_PRODUCTO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_CATEGORIA      VARCHAR(100) NOT NULL,
    DESCRIPCION           VARCHAR(255),
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CATEGORIA_PRODUCTO_TB PRIMARY KEY (ID_CATEGORIA_PRODUCTO),
    CONSTRAINT FK_PUBROCK_CATEGORIA_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PRODUCTO_TB (
    ID_PRODUCTO            INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PRODUCTO        VARCHAR(100) NOT NULL,
    DESCRIPCION            VARCHAR(255),
    CODIGO_BARRAS          VARCHAR(100),
    PRECIO_VENTA           DECIMAL(10,2) NOT NULL DEFAULT 0,
    FECHA_VENCIMIENTO      DATE,
    ID_CATEGORIA_PRODUCTO  INT NOT NULL,
    ID_PROVEEDOR           INT,
    ID_ESTADO              INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PRODUCTO_TB PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_PRODUCTO_PRECIO CHECK (PRECIO_VENTA >= 0),
    CONSTRAINT FK_PUBROCK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES PUBROCK_CATEGORIA_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PRODUCTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PUBROCK_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FK_PUBROCK_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

-- Codigo de barras unico solo cuando existe (muchos productos de menu
-- de un restaurante no tienen codigo de barras real).
CREATE UNIQUE INDEX UQ_PUBROCK_PRODUCTO_CODIGO_BARRAS ON PUBROCK_PRODUCTO_TB(CODIGO_BARRAS) WHERE CODIGO_BARRAS IS NOT NULL;
GO

CREATE TABLE PUBROCK_INVENTARIO_TB (
    ID_INVENTARIO               INT IDENTITY(1,1) NOT NULL,
    STOCK_ACTUAL                INT NOT NULL DEFAULT 0,
    STOCK_MINIMO                INT NOT NULL DEFAULT 0,
    STOCK_MAXIMO                INT NOT NULL DEFAULT 0,
    FECHA_ULTIMA_ACTUALIZACION  DATE NOT NULL DEFAULT GETDATE(),
    ID_PRODUCTO                 INT NOT NULL,
    ID_ESTADO                   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_INVENTARIO_TB PRIMARY KEY (ID_INVENTARIO),
    CONSTRAINT UQ_PUBROCK_INVENTARIO_PRODUCTO UNIQUE (ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_ACTUAL CHECK (STOCK_ACTUAL >= 0),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_MINIMO CHECK (STOCK_MINIMO >= 0),
    CONSTRAINT CK_PUBROCK_INVENTARIO_STOCK_MAXIMO CHECK (STOCK_MAXIMO >= STOCK_MINIMO),
    CONSTRAINT FK_PUBROCK_INVENTARIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB (
    ID_TIPO_MOVIMIENTO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB PRIMARY KEY (ID_TIPO_MOVIMIENTO),
    CONSTRAINT FK_PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO_INVENTARIO INT IDENTITY(1,1) NOT NULL,
    FECHA_MOVIMIENTO         DATE NOT NULL DEFAULT GETDATE(),
    CANTIDAD                 INT NOT NULL,
    OBSERVACION              VARCHAR(255),
    ID_INVENTARIO            INT NOT NULL,
    ID_TIPO_MOVIMIENTO       INT NOT NULL,
    ID_ESTADO                INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MOVIMIENTO_INVENTARIO_TB PRIMARY KEY (ID_MOVIMIENTO_INVENTARIO),
    CONSTRAINT CK_PUBROCK_MOVIMIENTO_INVENTARIO_CANTIDAD CHECK (CANTIDAD <> 0),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_INVENTARIO FOREIGN KEY (ID_INVENTARIO) REFERENCES PUBROCK_INVENTARIO_TB(ID_INVENTARIO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_TIPO FOREIGN KEY (ID_TIPO_MOVIMIENTO) REFERENCES PUBROCK_TIPO_MOVIMIENTO_INVENTARIO_TB(ID_TIPO_MOVIMIENTO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_INVENTARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 7: COMPRAS
-- =====================================================================
CREATE TABLE PUBROCK_COMPRA_TB (
    ID_COMPRA    INT IDENTITY(1,1) NOT NULL,
    FECHA_COMPRA DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_COMPRA DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_PROVEEDOR INT NOT NULL,
    ID_EMPLEADO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_COMPRA_TB PRIMARY KEY (ID_COMPRA),
    CONSTRAINT CK_PUBROCK_COMPRA_TOTAL CHECK (TOTAL_COMPRA >= 0),
    CONSTRAINT FK_PUBROCK_COMPRA_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PUBROCK_PROVEEDOR_TB(ID_PROVEEDOR),
    CONSTRAINT FK_PUBROCK_COMPRA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_COMPRA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_COMPRA_TB (
    ID_DETALLE_COMPRA INT IDENTITY(1,1) NOT NULL,
    CANTIDAD          INT NOT NULL,
    COSTO_UNITARIO    DECIMAL(10,2) NOT NULL,
    SUBTOTAL          DECIMAL(10,2) NOT NULL,
    ID_COMPRA         INT NOT NULL,
    ID_PRODUCTO       INT NOT NULL,
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_COMPRA_TB PRIMARY KEY (ID_DETALLE_COMPRA),
    CONSTRAINT CK_PUBROCK_DETALLE_COMPRA_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_COMPRA_COSTO CHECK (COSTO_UNITARIO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES PUBROCK_COMPRA_TB(ID_COMPRA),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_COMPRA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 8: VENTAS
-- =====================================================================
CREATE TABLE PUBROCK_VENTA_TB (
    ID_VENTA     INT IDENTITY(1,1) NOT NULL,
    FECHA_VENTA  DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_VENTA  DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_CLIENTE   INT,
    ID_EMPLEADO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_VENTA_TB PRIMARY KEY (ID_VENTA),
    CONSTRAINT CK_PUBROCK_VENTA_TOTAL CHECK (TOTAL_VENTA >= 0),
    CONSTRAINT FK_PUBROCK_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_VENTA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_VENTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_VENTA_TB (
    ID_DETALLE_VENTA INT IDENTITY(1,1) NOT NULL,
    CANTIDAD         INT NOT NULL,
    PRECIO_UNITARIO  DECIMAL(10,2) NOT NULL,
    SUBTOTAL         DECIMAL(10,2) NOT NULL,
    ID_VENTA         INT NOT NULL,
    ID_PRODUCTO      INT NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_VENTA_TB PRIMARY KEY (ID_DETALLE_VENTA),
    CONSTRAINT CK_PUBROCK_DETALLE_VENTA_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_VENTA_PRECIO CHECK (PRECIO_UNITARIO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_VENTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 9: FACTURACION
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_PAGO_TB (
    ID_TIPO_PAGO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION  VARCHAR(100) NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_PAGO_TB PRIMARY KEY (ID_TIPO_PAGO),
    CONSTRAINT FK_PUBROCK_TIPO_PAGO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_FACTURA_TB (
    ID_FACTURA     INT IDENTITY(1,1) NOT NULL,
    NUMERO_FACTURA VARCHAR(100) NOT NULL,
    FECHA_FACTURA  DATE NOT NULL DEFAULT GETDATE(),
    MONTO_TOTAL    DECIMAL(10,2) NOT NULL,
    ID_VENTA       INT NOT NULL,
    ID_TIPO_PAGO   INT NOT NULL,
    ID_ESTADO      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_FACTURA_TB PRIMARY KEY (ID_FACTURA),
    CONSTRAINT UQ_PUBROCK_FACTURA_NUMERO UNIQUE (NUMERO_FACTURA),
    CONSTRAINT CK_PUBROCK_FACTURA_MONTO CHECK (MONTO_TOTAL >= 0),
    CONSTRAINT FK_PUBROCK_FACTURA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_FACTURA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES PUBROCK_TIPO_PAGO_TB(ID_TIPO_PAGO),
    CONSTRAINT FK_PUBROCK_FACTURA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 10: DEVOLUCIONES
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_DEVOLUCION_TB (
    ID_TIPO_DEVOLUCION INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_DEVOLUCION_TB PRIMARY KEY (ID_TIPO_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_TIPO_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DEVOLUCION_TB (
    ID_DEVOLUCION       INT IDENTITY(1,1) NOT NULL,
    FECHA_DEVOLUCION    DATE NOT NULL DEFAULT GETDATE(),
    MOTIVO_GENERAL      VARCHAR(255),
    ID_VENTA            INT NOT NULL,
    ID_CLIENTE          INT,
    ID_EMPLEADO         INT NOT NULL,
    ID_TIPO_DEVOLUCION  INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DEVOLUCION_TB PRIMARY KEY (ID_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_TIPO FOREIGN KEY (ID_TIPO_DEVOLUCION) REFERENCES PUBROCK_TIPO_DEVOLUCION_TB(ID_TIPO_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_DEVOLUCION_TB (
    ID_DETALLE_DEVOLUCION INT IDENTITY(1,1) NOT NULL,
    CANTIDAD              INT NOT NULL,
    MONTO_DEVUELTO        DECIMAL(10,2) NOT NULL,
    ID_DEVOLUCION         INT NOT NULL,
    ID_PRODUCTO           INT NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_DEVOLUCION_TB PRIMARY KEY (ID_DETALLE_DEVOLUCION),
    CONSTRAINT CK_PUBROCK_DETALLE_DEVOLUCION_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT CK_PUBROCK_DETALLE_DEVOLUCION_MONTO CHECK (MONTO_DEVUELTO >= 0),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_DEVOLUCION FOREIGN KEY (ID_DEVOLUCION) REFERENCES PUBROCK_DEVOLUCION_TB(ID_DEVOLUCION),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_DEVOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 11: CAJA Y MOVIMIENTOS FINANCIEROS
-- =====================================================================
CREATE TABLE PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB (
    ID_TIPO_MOVIMIENTO_FINANCIERO INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION                    VARCHAR(100) NOT NULL,
    ID_ESTADO                      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB PRIMARY KEY (ID_TIPO_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_MOVIMIENTO_FINANCIERO_TB (
    ID_MOVIMIENTO_FINANCIERO      INT IDENTITY(1,1) NOT NULL,
    FECHA_MOVIMIENTO              DATE NOT NULL DEFAULT GETDATE(),
    DESCRIPCION                   VARCHAR(255),
    MONTO                         DECIMAL(10,2) NOT NULL,
    ID_TIPO_MOVIMIENTO_FINANCIERO INT NOT NULL,
    ID_VENTA                      INT,
    ID_EMPLEADO                   INT NOT NULL,
    ID_ESTADO                     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MOVIMIENTO_FINANCIERO_TB PRIMARY KEY (ID_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_TIPO FOREIGN KEY (ID_TIPO_MOVIMIENTO_FINANCIERO) REFERENCES PUBROCK_TIPO_MOVIMIENTO_FINANCIERO_TB(ID_TIPO_MOVIMIENTO_FINANCIERO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_MOVIMIENTO_FINANCIERO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CAJA_TB (
    ID_CAJA        INT IDENTITY(1,1) NOT NULL,
    FECHA_APERTURA DATE NOT NULL DEFAULT GETDATE(),
    MONTO_INICIAL  DECIMAL(10,2) NOT NULL DEFAULT 0,
    FECHA_CIERRE   DATE,
    MONTO_FINAL    DECIMAL(10,2),
    DIFERENCIA     DECIMAL(10,2),
    ID_EMPLEADO    INT NOT NULL,
    ID_ESTADO      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CAJA_TB PRIMARY KEY (ID_CAJA),
    CONSTRAINT CK_PUBROCK_CAJA_MONTO_INICIAL CHECK (MONTO_INICIAL >= 0),
    CONSTRAINT FK_PUBROCK_CAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_CAJA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_CIERRE_CAJA_TB (
    ID_CIERRE_CAJA  INT IDENTITY(1,1) NOT NULL,
    FECHA_CIERRE    DATE NOT NULL DEFAULT GETDATE(),
    TOTAL_VENTAS    DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL_INGRESOS  DECIMAL(10,2) NOT NULL DEFAULT 0,
    TOTAL_EGRESOS   DECIMAL(10,2) NOT NULL DEFAULT 0,
    BALANCE_FINAL   DECIMAL(10,2) NOT NULL DEFAULT 0,
    ID_EMPLEADO     INT NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_CIERRE_CAJA_TB PRIMARY KEY (ID_CIERRE_CAJA),
    CONSTRAINT FK_PUBROCK_CIERRE_CAJA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_CIERRE_CAJA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_BITACORA_TB (
    ID_BITACORA       INT IDENTITY(1,1) NOT NULL,
    FECHA_HORA        DATETIME NOT NULL DEFAULT GETDATE(),
    ACCION_REALIZADA  VARCHAR(255) NOT NULL,
    DESCRIPCION       VARCHAR(500),
    CEDULA            VARCHAR(20),
    ID_ESTADO         INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_BITACORA_TB PRIMARY KEY (ID_BITACORA),
    CONSTRAINT FK_PUBROCK_BITACORA_USUARIO FOREIGN KEY (CEDULA) REFERENCES PUBROCK_USUARIO_TB(CEDULA),
    CONSTRAINT FK_PUBROCK_BITACORA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 12: IMPUESTOS
-- =====================================================================
CREATE TABLE PUBROCK_IMPUESTO_TB (
    ID_IMPUESTO     INT IDENTITY(1,1) NOT NULL,
    NOMBRE_IMPUESTO VARCHAR(100) NOT NULL,
    PORCENTAJE      DECIMAL(5,2) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_IMPUESTO_TB PRIMARY KEY (ID_IMPUESTO),
    CONSTRAINT CK_PUBROCK_IMPUESTO_PORCENTAJE CHECK (PORCENTAJE BETWEEN 0 AND 100),
    CONSTRAINT FK_PUBROCK_IMPUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_VENTA_IMPUESTO_TB (
    ID_VENTA        INT NOT NULL,
    ID_IMPUESTO     INT NOT NULL,
    MONTO_IMPUESTO  DECIMAL(10,2) NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_VENTA_IMPUESTO_TB PRIMARY KEY (ID_VENTA, ID_IMPUESTO),
    CONSTRAINT CK_PUBROCK_VENTA_IMPUESTO_MONTO CHECK (MONTO_IMPUESTO >= 0),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_IMPUESTO FOREIGN KEY (ID_IMPUESTO) REFERENCES PUBROCK_IMPUESTO_TB(ID_IMPUESTO),
    CONSTRAINT FK_PUBROCK_VENTA_IMPUESTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 13: PROMOCIONES
-- =====================================================================
CREATE TABLE PUBROCK_PROMOCION_TB (
    ID_PROMOCION          INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PROMOCION      VARCHAR(100) NOT NULL,
    DESCRIPCION           VARCHAR(255),
    PORCENTAJE_DESCUENTO  DECIMAL(5,2) NOT NULL,
    FECHA_INICIO          DATE NOT NULL,
    FECHA_FIN             DATE NOT NULL,
    ID_ESTADO             INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROMOCION_TB PRIMARY KEY (ID_PROMOCION),
    CONSTRAINT CK_PUBROCK_PROMOCION_PORCENTAJE CHECK (PORCENTAJE_DESCUENTO BETWEEN 0 AND 100),
    CONSTRAINT CK_PUBROCK_PROMOCION_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_PROMOCION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_PROMOCION_PRODUCTO_TB (
    ID_PROMOCION INT NOT NULL,
    ID_PRODUCTO  INT NOT NULL,
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_PROMOCION_PRODUCTO_TB PRIMARY KEY (ID_PROMOCION, ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES PUBROCK_PROMOCION_TB(ID_PROMOCION),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_PROMOCION_PRODUCTO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 14: REPORTES
-- =====================================================================
CREATE TABLE PUBROCK_FORMATO_REPORTE_TB (
    ID_FORMATO_REPORTE INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION         VARCHAR(100) NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_FORMATO_REPORTE_TB PRIMARY KEY (ID_FORMATO_REPORTE),
    CONSTRAINT FK_PUBROCK_FORMATO_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_TIPO_REPORTE_TB (
    ID_TIPO_REPORTE INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION      VARCHAR(100) NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_TIPO_REPORTE_TB PRIMARY KEY (ID_TIPO_REPORTE),
    CONSTRAINT FK_PUBROCK_TIPO_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_REPORTE_TB (
    ID_REPORTE          INT IDENTITY(1,1) NOT NULL,
    FECHA_GENERACION    DATE NOT NULL DEFAULT GETDATE(),
    FECHA_INICIO        DATE NOT NULL,
    FECHA_FIN           DATE NOT NULL,
    ID_TIPO_REPORTE     INT NOT NULL,
    ID_EMPLEADO         INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    ID_FORMATO_REPORTE  INT NOT NULL,
    CONSTRAINT PK_PUBROCK_REPORTE_TB PRIMARY KEY (ID_REPORTE),
    CONSTRAINT CK_PUBROCK_REPORTE_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_REPORTE_TIPO_REPORTE FOREIGN KEY (ID_TIPO_REPORTE) REFERENCES PUBROCK_TIPO_REPORTE_TB(ID_TIPO_REPORTE),
    CONSTRAINT FK_PUBROCK_REPORTE_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_REPORTE_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO),
    CONSTRAINT FK_PUBROCK_REPORTE_FORMATO FOREIGN KEY (ID_FORMATO_REPORTE) REFERENCES PUBROCK_FORMATO_REPORTE_TB(ID_FORMATO_REPORTE)
);
GO


-- =====================================================================
-- SECCION 15: CONTENIDO DE MARKETING
-- =====================================================================
CREATE TABLE PUBROCK_MARKETING_TB (
    ID_PUBLICACION   INT IDENTITY(1,1) NOT NULL,
    TITULO           VARCHAR(150) NOT NULL,
    TIPO_CONTENIDO   VARCHAR(50) NOT NULL,
    DESCRIPCION      VARCHAR(500) NOT NULL,
    FECHA_INICIO     DATE NOT NULL,
    FECHA_FIN        DATE NOT NULL,
    PRECIO           DECIMAL(10,2) NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    FECHA_REGISTRO   DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_PUBROCK_MARKETING_TB PRIMARY KEY (ID_PUBLICACION),
    CONSTRAINT CK_PUBROCK_MARKETING_FECHAS CHECK (FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT FK_PUBROCK_MARKETING_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 16: MESAS Y RESERVACIONES
-- =====================================================================
CREATE TABLE PUBROCK_MESA_TB (
    ID_MESA     INT IDENTITY(1,1) NOT NULL,
    NUMERO_MESA INT NOT NULL,
    CAPACIDAD   INT NOT NULL,
    ID_ESTADO   INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_MESA_TB PRIMARY KEY (ID_MESA),
    CONSTRAINT UQ_PUBROCK_MESA_NUMERO UNIQUE (NUMERO_MESA),
    CONSTRAINT CK_PUBROCK_MESA_CAPACIDAD CHECK (CAPACIDAD > 0),
    CONSTRAINT FK_PUBROCK_MESA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_RESERVACION_TB (
    ID_RESERVACION      INT IDENTITY(1,1) NOT NULL,
    FECHA_RESERVACION   DATE NOT NULL,
    HORA_INICIO         TIME NOT NULL,
    HORA_FIN            TIME NOT NULL,
    CANTIDAD_PERSONAS   INT NOT NULL,
    OBSERVACIONES       VARCHAR(500),
    ID_CLIENTE          INT NOT NULL,
    ID_MESA             INT NOT NULL,
    ID_ESTADO           INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_RESERVACION_TB PRIMARY KEY (ID_RESERVACION),
    CONSTRAINT CK_PUBROCK_RESERVACION_PERSONAS CHECK (CANTIDAD_PERSONAS > 0),
    CONSTRAINT CK_PUBROCK_RESERVACION_HORAS CHECK (HORA_FIN > HORA_INICIO),
    CONSTRAINT FK_PUBROCK_RESERVACION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES PUBROCK_CLIENTE_TB(ID_CLIENTE),
    CONSTRAINT FK_PUBROCK_RESERVACION_MESA FOREIGN KEY (ID_MESA) REFERENCES PUBROCK_MESA_TB(ID_MESA),
    CONSTRAINT FK_PUBROCK_RESERVACION_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_HORARIO_TB (
    ID_HORARIO    INT IDENTITY(1,1) NOT NULL,
    DIA_SEMANA    VARCHAR(50) NOT NULL,
    HORA_ENTRADA  TIME NOT NULL,
    HORA_SALIDA   TIME NOT NULL,
    ID_EMPLEADO   INT NOT NULL,
    ID_ESTADO     INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_HORARIO_TB PRIMARY KEY (ID_HORARIO),
    CONSTRAINT CK_PUBROCK_HORARIO_HORAS CHECK (HORA_SALIDA > HORA_ENTRADA),
    CONSTRAINT FK_PUBROCK_HORARIO_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES PUBROCK_EMPLEADO_TB(ID_EMPLEADO),
    CONSTRAINT FK_PUBROCK_HORARIO_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 17: ORDENES
-- =====================================================================
CREATE TABLE PUBROCK_ESTADO_ORDEN_TB (
    ID_ESTADO_ORDEN INT IDENTITY(1,1) NOT NULL,
    DESCRIPCION      VARCHAR(100) NOT NULL,
    ID_ESTADO        INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ESTADO_ORDEN_TB PRIMARY KEY (ID_ESTADO_ORDEN),
    CONSTRAINT FK_PUBROCK_ESTADO_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_ORDEN_TB (
    ID_ORDEN        INT IDENTITY(1,1) NOT NULL,
    FECHA_ORDEN     DATE NOT NULL DEFAULT GETDATE(),
    OBSERVACIONES   VARCHAR(500),
    ID_VENTA        INT NOT NULL,
    ID_ESTADO_ORDEN INT NOT NULL,
    ID_ESTADO       INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_ORDEN_TB PRIMARY KEY (ID_ORDEN),
    CONSTRAINT FK_PUBROCK_ORDEN_VENTA FOREIGN KEY (ID_VENTA) REFERENCES PUBROCK_VENTA_TB(ID_VENTA),
    CONSTRAINT FK_PUBROCK_ORDEN_ESTADO_ORDEN FOREIGN KEY (ID_ESTADO_ORDEN) REFERENCES PUBROCK_ESTADO_ORDEN_TB(ID_ESTADO_ORDEN),
    CONSTRAINT FK_PUBROCK_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO

CREATE TABLE PUBROCK_DETALLE_ORDEN_TB (
    ID_ORDEN     INT NOT NULL,
    ID_PRODUCTO  INT NOT NULL,
    CANTIDAD     INT NOT NULL,
    OBSERVACION  VARCHAR(255),
    ID_ESTADO    INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_PUBROCK_DETALLE_ORDEN_TB PRIMARY KEY (ID_ORDEN, ID_PRODUCTO),
    CONSTRAINT CK_PUBROCK_DETALLE_ORDEN_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES PUBROCK_ORDEN_TB(ID_ORDEN),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PUBROCK_PRODUCTO_TB(ID_PRODUCTO),
    CONSTRAINT FK_PUBROCK_DETALLE_ORDEN_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES PUBROCK_ESTADO_TB(ID_ESTADO)
);
GO


-- =====================================================================
-- SECCION 18: INDICES DE APOYO SOBRE LLAVES FORANEAS
-- SQL Server NO crea automaticamente un indice sobre las columnas FK
-- (solo sobre la PK referenciada). Sin estos indices, los JOIN y los
-- borrados/actualizaciones en cascada logica recorren la tabla
-- completa. Se agregan sobre las columnas mas consultadas por un
-- sistema de punto de venta / restaurante.
-- =====================================================================
CREATE INDEX IX_PUBROCK_PROVINCIA_PAIS               ON PUBROCK_PROVINCIA_TB(ID_PAIS);
CREATE INDEX IX_PUBROCK_CANTON_PROVINCIA              ON PUBROCK_CANTON_TB(ID_PROVINCIA);
CREATE INDEX IX_PUBROCK_DISTRITO_CANTON               ON PUBROCK_DISTRITO_TB(ID_CANTON);
CREATE INDEX IX_PUBROCK_USUARIO_TIPO_USUARIO          ON PUBROCK_USUARIO_TB(ID_TIPO_USUARIO);
CREATE INDEX IX_PUBROCK_DIRECCION_PAIS                ON PUBROCK_DIRECCION_TB(ID_PAIS);
CREATE INDEX IX_PUBROCK_DIRECCION_PROVINCIA           ON PUBROCK_DIRECCION_TB(ID_PROVINCIA);
CREATE INDEX IX_PUBROCK_DIRECCION_CANTON              ON PUBROCK_DIRECCION_TB(ID_CANTON);
CREATE INDEX IX_PUBROCK_DIRECCION_DISTRITO            ON PUBROCK_DIRECCION_TB(ID_DISTRITO);
CREATE INDEX IX_PUBROCK_EMPLEADO_PUESTO               ON PUBROCK_EMPLEADO_TB(ID_PUESTO);
CREATE INDEX IX_PUBROCK_USUARIO_SISTEMA_EMPLEADO      ON PUBROCK_USUARIO_SISTEMA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_USUARIO_SISTEMA_ROL           ON PUBROCK_USUARIO_SISTEMA_TB(ID_ROL);
CREATE INDEX IX_PUBROCK_REGISTRO_ACTIVIDAD_USUARIO    ON PUBROCK_REGISTRO_ACTIVIDAD_TB(ID_USUARIO_SISTEMA);
CREATE INDEX IX_PUBROCK_PRODUCTO_CATEGORIA            ON PUBROCK_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO);
CREATE INDEX IX_PUBROCK_PRODUCTO_PROVEEDOR            ON PUBROCK_PRODUCTO_TB(ID_PROVEEDOR);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_INVENTARIO_INVENT  ON PUBROCK_MOVIMIENTO_INVENTARIO_TB(ID_INVENTARIO);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_INVENTARIO_TIPO    ON PUBROCK_MOVIMIENTO_INVENTARIO_TB(ID_TIPO_MOVIMIENTO);
CREATE INDEX IX_PUBROCK_COMPRA_PROVEEDOR              ON PUBROCK_COMPRA_TB(ID_PROVEEDOR);
CREATE INDEX IX_PUBROCK_COMPRA_EMPLEADO               ON PUBROCK_COMPRA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_COMPRA_COMPRA         ON PUBROCK_DETALLE_COMPRA_TB(ID_COMPRA);
CREATE INDEX IX_PUBROCK_DETALLE_COMPRA_PRODUCTO       ON PUBROCK_DETALLE_COMPRA_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_VENTA_CLIENTE                 ON PUBROCK_VENTA_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_VENTA_EMPLEADO                ON PUBROCK_VENTA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_VENTA_VENTA           ON PUBROCK_DETALLE_VENTA_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_DETALLE_VENTA_PRODUCTO        ON PUBROCK_DETALLE_VENTA_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_FACTURA_VENTA                 ON PUBROCK_FACTURA_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_FACTURA_TIPO_PAGO             ON PUBROCK_FACTURA_TB(ID_TIPO_PAGO);
CREATE INDEX IX_PUBROCK_DEVOLUCION_VENTA              ON PUBROCK_DEVOLUCION_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_DEVOLUCION_CLIENTE            ON PUBROCK_DEVOLUCION_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_DEVOLUCION_EMPLEADO           ON PUBROCK_DEVOLUCION_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_DETALLE_DEVOLUCION_DEVOLUCION ON PUBROCK_DETALLE_DEVOLUCION_TB(ID_DEVOLUCION);
CREATE INDEX IX_PUBROCK_DETALLE_DEVOLUCION_PRODUCTO   ON PUBROCK_DETALLE_DEVOLUCION_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_FINANCIERO_VENTA   ON PUBROCK_MOVIMIENTO_FINANCIERO_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_MOVIMIENTO_FINANCIERO_EMPLEADO ON PUBROCK_MOVIMIENTO_FINANCIERO_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_CAJA_EMPLEADO                 ON PUBROCK_CAJA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_CIERRE_CAJA_EMPLEADO          ON PUBROCK_CIERRE_CAJA_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_BITACORA_CEDULA               ON PUBROCK_BITACORA_TB(CEDULA);
CREATE INDEX IX_PUBROCK_VENTA_IMPUESTO_IMPUESTO       ON PUBROCK_VENTA_IMPUESTO_TB(ID_IMPUESTO);
CREATE INDEX IX_PUBROCK_PROMOCION_PRODUCTO_PRODUCTO   ON PUBROCK_PROMOCION_PRODUCTO_TB(ID_PRODUCTO);
CREATE INDEX IX_PUBROCK_REPORTE_TIPO_REPORTE          ON PUBROCK_REPORTE_TB(ID_TIPO_REPORTE);
CREATE INDEX IX_PUBROCK_REPORTE_EMPLEADO              ON PUBROCK_REPORTE_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_REPORTE_FORMATO               ON PUBROCK_REPORTE_TB(ID_FORMATO_REPORTE);
CREATE INDEX IX_PUBROCK_RESERVACION_CLIENTE           ON PUBROCK_RESERVACION_TB(ID_CLIENTE);
CREATE INDEX IX_PUBROCK_RESERVACION_MESA              ON PUBROCK_RESERVACION_TB(ID_MESA);
CREATE INDEX IX_PUBROCK_HORARIO_EMPLEADO              ON PUBROCK_HORARIO_TB(ID_EMPLEADO);
CREATE INDEX IX_PUBROCK_ORDEN_VENTA                   ON PUBROCK_ORDEN_TB(ID_VENTA);
CREATE INDEX IX_PUBROCK_ORDEN_ESTADO_ORDEN            ON PUBROCK_ORDEN_TB(ID_ESTADO_ORDEN);
CREATE INDEX IX_PUBROCK_DETALLE_ORDEN_PRODUCTO        ON PUBROCK_DETALLE_ORDEN_TB(ID_PRODUCTO);
GO


-- =====================================================================
-- FIN DEL SCRIPT
-- Se retiraron intencionalmente del final del script original los
-- siguientes comandos, por ser destructivos/peligrosos y no tener
-- ningun lugar en un script de creacion de base de datos:
--   ALTER DATABASE PUBROCK_CR SET EMERGENCY;
--   ALTER DATABASE PUBROCK_CR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--   DBCC CHECKDB(PUBROCK_CR, REPAIR_ALLOW_DATA_LOSS);
--   ALTER DATABASE PUBROCK_CR SET MULTI_USER;
-- Ver PUBROCK_REPORTE_CAMBIOS.md para el detalle completo.
-- =====================================================================
PRINT 'BASE DE DATOS PUBROCK_CR CREADA CORRECTAMENTE.';
GO
